<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Pharmacy"));?></div></td>
   <td><?php echo $this->pharmacyName;?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Date of Visit"));?></div></td>
   <td><?php echo $this->formModel->getDateOfVisit();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Patient"));?></div></td>
   <td><?php printf("%s (%s %s)", $this->patientModel->getIdentifier(), $this->patientModel->getLastName(), $this->patientModel->getFirstName());?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Date of Birth"));?></div></td>
   <td><?php echo $this->patientModel->getBirthdate();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("HIV Status"));?></div></td>
   <td><?php if(array_key_exists($this->formModel->getHivStatus(), $this->hivStatuses)) echo $this->hivStatuses[$this->formModel->getHivStatus()];?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Form Status"));?></div></td>
   <td><?php echo $this->formModel->getIsCommited() ? $this->translate(_("Final Result")) : $this->translate(_("Draft"));?></td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Referral Services Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Referred in?"));?></div></td>
   <td><?php echo $this->formModel->getIsReferredIn() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr id="row_referred_in">
   <td></td>
   <td>
<?php
    foreach($this->referredInList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Referred out?"));?></div></td>
   <td><?php echo $this->formModel->getIsReferredOut() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td>
<?php
    foreach($this->referredOutList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Was the referral completed?"));?></div></td>
   <td><?php echo $this->formModel->getIsReferralCompleted() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("HIV risk assessment & counseling done?"));?></div></td>
   <td><?php echo $this->formModel->getIsHivRiskAssesmentDone() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("HCT Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("HIV Testing done?"));?></div></td>
   <td><?php echo $this->formModel->getIsHtcDone() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td><?php echo $this->htcResultName;?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Was the client Counseled, Tested & received results?"));?></div></td>
   <td><?php echo $this->formModel->getIsClientReceivedHtc() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Was the HCT done in your Pharmacy?"));?></div></td>
   <td><?php echo $this->formModel->getIsHtcDoneInCurrentPharmacy() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Services Provided Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Palliative Care Services to PLWHAs"));?></div></td>
   <td><?php echo $this->formModel->getIsPalliativeServicesToPlwha() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td>
<?php
    foreach($this->palliativeCareTypeList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("STI Services"));?></div></td>
   <td><?php echo $this->formModel->getIsStiServices() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td>
<?php
    foreach($this->stiTypeList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Reproductive Health Services"));?></div></td>
   <td><?php echo $this->formModel->getIsReproductiveHealthServices() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td>
<?php
    foreach($this->reproductiveHealthTypeList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Tuberculosis Services"));?></div></td>
   <td><?php echo $this->formModel->getIsTuberculosisServices() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td></td>
   <td>
<?php
    foreach($this->tuberculosisTypeList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("OVC Care and Support Services"));?></div></td>
   <td><?php echo $this->formModel->getIsOvcServices() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr id="row_ovc_type">
   <td></td>
   <td>
<?php
    foreach($this->ovcTypeList as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>
