<?php
$this->headScript()->appendFile('/js/internalAddress.js');
$this->headScript()->appendFile('/js/pageAsDlg.js');
$this->headScript()->appendFile('/js/pharmacyCtrl.js');
$this->headScript()->appendFile('/js/patientCtrl.js');
$this->headScript()->appendFile('/js/jquery/plugin/showLoading/jquery.showLoading.min.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.ui.position.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.contextMenu.js');

$this->headLink()->appendStylesheet('/css/showLoading.css');
$this->headLink()->appendStylesheet('/js/jquery/plugin/contextMenu/jquery.contextMenu.css');

$textForEmptyAdrStopDate = $this->translate(_("Ongoing"));
?>
<style type="text/css" title="currentStyle">
a {
    cursor: pointer;
    text-decoration: underline;
}
</style>

<script type="text/javascript" charset="utf-8">
var g_selectedPharmacy = '<?php echo $this->idPharmacy?>';
var g_dictEntities = new Array();
<?php foreach($this->dictEntities as $key=>$values) :?>
    g_dictEntities[<?php echo $key;?>] = [<?php if(is_array($values)) echo join(" , ", $values);?>];
<?php endforeach; ?>

	function checkIsReferredIn()
	{
		if(0 == $('input:radio[name=is_referred_in]:checked').val()) {
			$('#row_referred_in').hide();
		}
		else {
			$('#row_referred_in').show();
		}
	}

	function checkIsReferredOut()
	{
		if(0 == $('input:radio[name=is_referred_out]:checked').val()) {
			$('#row_referred_out').hide();
		}
		else {
			$('#row_referred_out').show();
		}
	}

	function checkIsHtcDone()
	{
		if(0 == $('input:radio[name=is_htc_done]:checked').val()) {
			$('#row_htc_result_id').hide();
		}
		else {
			$('#row_htc_result_id').show();
		}
	}

	function checkIsPalliativeServicesToPlwha()
	{
		if(0 == $('input:radio[name=is_palliative_services_to_plwha]:checked').val()) {
			$('#row_palliative_care_type').hide();
		}
		else {
			$('#row_palliative_care_type').show();
		}
	}

	function checkIsStiServices()
	{
		if(0 == $('input:radio[name=is_sti_services]:checked').val()) {
			$('#row_sti_type').hide();
		}
		else {
			$('#row_sti_type').show();
		}
	}
	
	function checkIsReproductiveHealthServices()
	{
		if(0 == $('input:radio[name=is_reproductive_health_services]:checked').val()) {
			$('#row_reproductive_health_type').hide();
		}
		else {
			$('#row_reproductive_health_type').show();
		}
	}

	function checkIsTuberculosisServices()
	{
		if(0 == $('input:radio[name=is_tuberculosis_services]:checked').val()) {
			$('#row_tuberculosis_type').hide();
		}
		else {
			$('#row_tuberculosis_type').show();
		}
	}

	function checkIsOvcServices()
	{
		if(0 == $('input:radio[name=is_ovc_services]:checked').val()) {
			$('#row_ovc_type').hide();
		}
		else {
			$('#row_ovc_type').show();
		}
	}

	
    function updateErrorInfo(dlgId, message) {
	    var infoEl = $(dlgId + " .errorInfo");
	    if('' != message) {
	        infoEl.text(message).addClass("ui-state-highlight");
	    }
	    else {
	        infoEl.text('').removeClass("ui-state-highlight");
	    }
	      
	    setTimeout(function() {
	        infoEl.removeClass("ui-state-highlight", 1500);
	    }, 500 );
	}

    
    function cleanErrorInfo(dlgId) {
        updateErrorInfo(dlgId, '');
        $('#add-dict-entity-name').val("").removeClass("ui-state-error");
    }


    $(document).ready(function() {
		internalAddress.setUrlBase('<?php echo $this->url(array('controller' => '__controller__', "action" => "__action__"), null, true); ?>');

		i18n.init({
		    resGetPath: internalAddress.loadI18nDict()
		    ,dynamicLoad: true 
		    ,getAsync: false
		    ,lng: '<?php echo Zend_Registry::get('Zend_Locale');?>'
		    ,ns: 'js_resources'
		    ,fallbackLng: false
		});
		
		var newPharmacyDlg = pharmacyCtrl.init('id_pharmacy');
<?php if ($this->allow_create_pharmacy) : ?>
        pharmacyCtrl.configureAddLink('link-add-pharmacy');
<?php endif;?>     

        var newPatientDlg = patientCtrl.init('id_patient', 'patient_name');
<?php if ($this->allow_create_patient) : ?>
        patientCtrl.configureAddLink('link-add-patient');
<?php endif;?>

    	$('#main_form').submit(function() {
        	if(!$("#id_pharmacy option:selected").val()) {
            	alert('<?php echo $this->translate(_("Necessary to choose pharmacy"));?>');
            	$("#id_pharmacy").focus();
            	return false;
        	}
        	if(!$("#patient_name").val()) {
            	alert('<?php echo $this->translate(_("Necessary to choose patient"));?>');
            	$("#patient_name").focus();
            	return false;
        	}
        	if($("#patient_name").val() && !$("#id_patient").val()) {
            	alert('<?php echo $this->translate(_("Unknown patient"));?>');
            	$("#patient_name").focus();
            	return false;
        	}
        	if(!$('#date_of_visit').val()) {
            	alert('<?php echo $this->translate(_("Necessary to enter date of visit"));?>');
            	$("#date_of_visit").focus();
            	return false;
        	}
        	if('<?php echo $textForEmptyAdrStopDate?>' == $('#adr_stop_date').val()) {
        		$('#adr_stop_date').val('');
        	}
        	return true;
	    });

	    dictEntitiesCtrl.reload('#referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    dictEntitiesCtrl.reload('#referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    dictEntitiesCtrl.reload('#htc_result_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_HTC_RESULT;?>');
	    dictEntitiesCtrl.reload('#palliative_care_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_PALLIATIVE_CARE_TYPE;?>');
	    dictEntitiesCtrl.reload('#sti_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_STI_TYPE;?>');
	    dictEntitiesCtrl.reload('#reproductive_health_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REPRODUCTIVE_HEALTH_TYPE;?>');
	    dictEntitiesCtrl.reload('#tuberculosis_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_TUBERCULOSIS_TYPE;?>');
	    dictEntitiesCtrl.reload('#ovc_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_OVC_TYPE;?>');
	    
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('palliative_care_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_PALLIATIVE_CARE_TYPE;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('sti_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_STI_TYPE;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('reproductive_health_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REPRODUCTIVE_HEALTH_TYPE;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('tuberculosis_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_TUBERCULOSIS_TYPE;?>');
	    dictEntitiesCtrl.linkDynamicActionsToPharmDictCtrl('ovc_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_OVC_TYPE;?>');
	    

/*** START Bind of OnChange ***/        
        $('input[name = "is_referred_in"]').bind('change', function(){
            checkIsReferredIn();
        });
        $('input[name = "is_referred_out"]').bind('change', function(){
            checkIsReferredOut();
        });
        $('input[name = "is_htc_done"]').bind('change', function(){
            checkIsHtcDone();
        });
        $('input[name = "is_palliative_services_to_plwha"]').bind('change', function(){
            checkIsPalliativeServicesToPlwha();
        });
        $('input[name = "is_sti_services"]').bind('change', function(){
            checkIsStiServices();
        });
        $('input[name = "is_reproductive_health_services"]').bind('change', function(){
            checkIsReproductiveHealthServices();
        });
        $('input[name = "is_tuberculosis_services"]').bind('change', function(){
            checkIsTuberculosisServices();
        });
        $('input[name = "is_ovc_services"]').bind('change', function(){
            checkIsOvcServices();
        });
/*** END Bind of OnChange ***/        
        
        checkIsReferredIn();
        checkIsReferredOut();
        checkIsHtcDone();
        checkIsPalliativeServicesToPlwha();
        checkIsStiServices();
        checkIsReproductiveHealthServices();
        checkIsTuberculosisServices();
        checkIsOvcServices();
        
        $("#date_of_visit").datepicker({dateFormat : 'yy-mm-dd', appendText: "(yyyy-mm-dd)"});
});
</script>	


<?php if(!empty($this->error)) : ?>
<div class="form_errors"><?php echo $this->error;?></div>
<?php endif;?>
<form id="main_form" class="zend_form" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('action' => 'create', 'type' => $this->type));?>">
<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="required"><label for="id_pharmacy"><?php echo $this->translate(_("Pharmacy"));?></label></div></td>
   <td>
     <select name="id_pharmacy" id="id_pharmacy">
        <option value=''></option>
<?php
    foreach($this->pharmacies as $key=>$value) {
        $selectedStr = ($key == $this->idPharmacy) ? 'selected' : '';
        printf("<option value='%s' %s>%s</option>", $key, $selectedStr, $value);
    }
?>     
     </select>&nbsp;
<?php if ($this->allow_create_pharmacy) : ?>
     <a id="link-add-pharmacy" href="#"><?php echo $this->translate(_("Add Pharmacy"));?></a>
<?php endif;?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><label for="id_patient"><?php echo $this->translate(_("Patient"));?></label></div></td>
   <td>
     <input type="hidden" name="id_patient" id="id_patient" value="<?php echo $this->id_patient?>" />
     <input type="text" size="32" name="patient_name" id="patient_name" value="<?php echo $this->patientName;?>">&nbsp;     
<?php if ($this->allow_create_patient) : ?>
     <a id="link-add-patient" href="#"><?php echo $this->translate(_("Add Patient"));?></a>
<?php endif;?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><label for="date_of_visit"><?php echo $this->translate(_("Date of Visit"));?></label></div></td>
   <td>
     <input type="text" name="date_of_visit" id="date_of_visit" value="<?php echo $this->dateOfVisit;?>">     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Referral Services Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_in"><?php echo $this->translate(_("Referred in?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_in" id="is_referred_in_0" value="0" <?php if(!$this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_in" id="is_referred_in_1" value="1" <?php if($this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_in">
   <td></td>
   <td>
     <select name="referred_in[]" id="referred_in" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_in"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_out"><?php echo $this->translate(_("Referred out?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_out" id="is_referred_out_0" value="0" <?php if(!$this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_out" id="is_referred_out_1" value="1" <?php if($this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_out">
   <td></td>
   <td>
     <select name="referred_out[]" id="referred_out" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_out"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referral_completed"><?php echo $this->translate(_("Was the referral completed?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referral_completed" id="is_referral_completed_0" value="0" <?php if(!$this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referral_completed" id="is_referral_completed_1" value="1" <?php if($this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_hiv_risk_assesment_done"><?php echo $this->translate(_("HIV risk assessment & counseling done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_0" value="0" <?php if(!$this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_1" value="1" <?php if($this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("HCT Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done"><?php echo $this->translate(_("HIV Testing done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done" id="is_htc_done_0" value="0" <?php if(!$this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done" id="is_htc_done_1" value="1" <?php if($this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_htc_result_id">
   <td></td>
   <td>
     <select name="htc_result_id" id="htc_result_id">
     </select>&nbsp;
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_client_received_htc"><?php echo $this->translate(_("Was the client Counseled, Tested & received results?"));?></label></div></td>
   <td>
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_0" value="0" <?php if(!$this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_1" value="1" <?php if($this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done_in_current_pharmacy"><?php echo $this->translate(_("Was the HCT done in your Pharmacy?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_0" value="0" <?php if(!$this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_1" value="1" <?php if($this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Services Provided Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_palliative_services_to_plwha"><?php echo $this->translate(_("Palliative Care Services to PLWHAs"));?></label></div></td>
   <td>
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_0" value="0" <?php if(!$this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_1" value="1" <?php if($this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_palliative_care_type">
   <td></td>
   <td>
     <select name="palliative_care_type[]" id="palliative_care_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-palliative_care_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_sti_services"><?php echo $this->translate(_("STI Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_sti_services" id="is_sti_services_0" value="0" <?php if(!$this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_sti_services" id="is_sti_services_1" value="1" <?php if($this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_sti_type">
   <td></td>
   <td>
     <select name="sti_type[]" id="sti_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-sti_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_reproductive_health_services"><?php echo $this->translate(_("Reproductive Health Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_0" value="0" <?php if(!$this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_1" value="1" <?php if($this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_reproductive_health_type">
   <td></td>
   <td>
     <select name="reproductive_health_type[]" id="reproductive_health_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-reproductive_health_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_tuberculosis_services"><?php echo $this->translate(_("Tuberculosis Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_0" value="0" <?php if(!$this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_1" value="1" <?php if($this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_tuberculosis_type">
   <td></td>
   <td>
     <select name="tuberculosis_type[]" id="tuberculosis_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-tuberculosis_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_ovc_services"><?php echo $this->translate(_("OVC Care and Support Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_ovc_services" id="is_ovc_services_0" value="0" <?php if(!$this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_ovc_services" id="is_ovc_services_1" value="1" <?php if($this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_ovc_type">
   <td></td>
   <td>
     <select name="ovc_type[]" id="ovc_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-ovc_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
 </table>
</div>


<input type="submit" name="save" value="<?php echo $this->translate(_("Save"));?>"/>     
</form>
