<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Patient"));?></div></td>
   <td><?php printf("%s (%s %s)", $this->patientModel->getIdentifier(), $this->patientModel->getLastName(), $this->patientModel->getFirstName());?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Date of Visit"));?></div></td>
   <td><?php echo $this->formModel->getDateOfVisit();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Is pregnant"));?></div></td>
   <td><?php echo $this->formModel->getIsPregnant() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Did client receive prescription in this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsReceivePrescription() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
 </table>
</div>


<div class="tab_header"><?php echo $this->translate(_("Medication Error Screening Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Is patient screened for Medication Error in this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsMedErrorScreened() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Is there Medication Error identified at this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsMedErrorIdentified() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Type of Medication Error"));?></div></td>
   <td>
<?php
    foreach($this->medErrorTypes as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>



<div class="tab_header"><?php echo $this->translate(_("Adherence Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Is patient screened for Medication Adherence Related problem(s) in this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsMedAdhProblemScreened() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_med_adh_problem_identified"><?php echo $this->translate(_("Is there Medication Adherence Related problem(s) identified at this visit?"));?></label></div></td>
   <td><?php echo $this->formModel->getIsMedAdhProblemIdentified() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Type of Medication Adherence Related problem(s)"));?></div></td>
   <td>
<?php
    foreach($this->medAdhProblems as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Medication Error / Adherence Intervention Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Medication Error / Adherence intervention provided at this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsAdhInterventionProvided() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Type of Medication Error / Adherence intervention provided"));?></div></td>
   <td>
<?php
    foreach($this->adhInterventions as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Medication Error / Adherence Intervention Outcome Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Type of Medication Error / Adherence intervention Outcome"));?></div></td>
   <td>
<?php
    foreach($this->adhInterventionOutcomes as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>
 
<div class="tab_header"><?php echo $this->translate(_("Suspected Adverse Drug Reactions (ADRs) Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Is patient screened for ADR symptoms at this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsAdrScreened() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Any signs/symptoms indicating NEW adverse drug reactions (ADRs) at this visit?"));?></div></td>
   <td><?php echo $this->formModel->getIsAdrSymptoms() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Types of ADRs severity grade"));?></div></td>
   <td><?php echo $this->severityName;?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("ADR Start Date"));?></div></td>
   <td><?php echo $this->formModel->getAdrStartDate();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("ADR Stop Date"));?></div></td>
   <td><?php echo $this->formModel->getAdrStopDate();?></td>
  </tr>
 </table>
</div>
 
<div class="tab_header"><?php echo $this->translate(_("Suspected ADR in system-organ classification"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("GIT/Hepatic System"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrHepatic as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Nervous System"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrNervous as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Cardiovascular System"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrCardiovascular as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Skin and Appendages"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrSkin as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Metabolic/Endocrine System"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrMetabolic as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Musculoskeletal"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrMusculoskeletal as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Systematic-General"));?></div></td>
   <td>
<?php
    foreach($this->suspectedAdrGeneral as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("ADR Intervention Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Adverse Drug Reaction intervention provided"));?></div></td>
   <td><?php echo $this->formModel->getIsAdrInterventionProvided() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("Types of ADR intervention"));?></div></td>
   <td>
<?php
    foreach($this->adrInterventions as $name) {
        echo $name.'<br/>';
    }
?>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><?php echo $this->translate(_("NAFDAC ADR reporting form filled"));?></div></td>
   <td><?php echo $this->formModel->getIsNafdacAdrFilled() ? $this->translate(_("Yes")) : $this->translate(_("No"));?></td>
  </tr>
 </table>
</div>
