<?php
$this->headLink()->appendStylesheet('/js/jquery/plugin/DataTables/css/jquery.dataTables.css');
//                 ->appendStylesheet('/js/jquery/plugin/DataTables/extras/ColReorder/css/ColReorder.css')
//                 ->appendStylesheet('/js/jquery/plugin/DataTables/extras/ColVis/css/ColVis.css');
                 
 $this->headScript()->appendFile('/js/jquery/plugin/DataTables/js/jquery.dataTables.js')
//                    ->appendFile('/js/jquery/plugin/DataTables/extras/ColReorder/js/ColReorder.js')
//                    ->appendFile('/js/jquery/plugin/DataTables/extras/ColVis/js/ColVis.js')
                    ->appendFile('/js/jquery/plugin/DataTables/extras/ColumnFilter/js/jquery.dataTables.columnFilter.js');

$sDom = '<"#list_toolbar">';                    
//$sDom .= "R";
//if($this->DataTable['chooseColumnVisibility']) {
//    $sDom .= 'C<"clear">';
//}
$sDom .= "lrtip";
                    
?>
<style type="text/css" title="currentStyle">
.clear { clear: both; }
.search_init { color: #999; }
.FixedHeader_Cloned th { background-color: white; }
thead th { text-align: left; }

.icon-edit { background-image:url(/img/actions/edit.gif) ! important; }
.icon-view { background-image:url(/img/actions/view.gif) ! important; }
.icon-delete { background-image:url(/img/actions/delete.gif) ! important; }
a.row_action { cursor: pointer; }
#list_toolbar_container {padding-top: 15px; padding-bottom: 15px;}
.list_toolbar_action {padding-right: 10px;}

</style>
        
<script type="text/javascript" charset="utf-8">


$(document).ready( function () {
    $('#list_div').html('<table cellpadding="0" cellspacing="0" border="0" id="list_table"></table>');
    var thead = jQuery('<thead/>');
    var trHeader = jQuery('<tr/>')
    var trFilter = jQuery('<tr/>')
    var bAddFilterRow = false;
    var filterParams = new Array();
    var aoColumns = new Array();

<?php
    $addActionColumn = array_key_exists('bActionsColumn', $this->DataTable) && $this->DataTable['bActionsColumn'] ? true : false;
    
    $addFilterRow = false;
    if($addActionColumn):
?>
    trHeader.append(jQuery('<th/>'));  /* column for actions */
    aoColumns[aoColumns.length] = {
            'mData'     : function ( source, type, val ) {return '';}
           ,'mRender'   : function ( data, type, full ) {
               var content = '';
               jQuery.each(full._row_actions_, function() {
                   var idPrefix = 'action_' + this.type + '_' + full.DT_RowId;
                   var showAction = true;
                   if(this.conditions) {
                       eval("showAction = ("+this.conditions+") ? true : false;");
                   }
                   if(showAction) {
                       content += '<a class="row_action" id="' + idPrefix + '">';
                       content += '<img src="/img/actions/'+this.type+'.gif" title="'+this.title+'">';
                       content += '<div class="ui-helper-hidden" id="'+idPrefix+'_url">'+this.url+'</div>'
                       if(this.askConfirm) {
                           content += '<div class="ui-helper-hidden" id="'+idPrefix+'_message">'+this.askConfirm+'</div>'
                       }
                       content += '</a>';
                   }
                   else {
                       content += '<img src="/img/actions/transparent_1x1.png" width="16" height="16"/>';
                   }
               });
                               
               return content;
           }       
           ,'sName'     : '__action__'
           ,'bSearchable' : false
           ,'bSortable' : false
           ,'bVisible'  : true
           ,'sWidth'    : '5%'
    };
<?php    
    endif;
    foreach($this->DataTable['columnsInfo'] as $key => $column):
?>
    trHeader.append(jQuery('<th/>', {'text' : '<?php echo $column['title'];?>'}));
    aoColumns[aoColumns.length] = {
            'mData'     : '<?php echo $key;?>'
           ,'sName'     : '<?php echo $key;?>'
           ,'sWidth'    : <?php echo array_key_exists('width', $column) ? "'".$column['width']."'" : 'null';?>
           ,'bSortable' : <?php echo !array_key_exists('sortable', $column) || $column['sortable'] ? 'true' : 'false';?>
           ,'bVisible'  : <?php echo !array_key_exists('visible', $column) || $column['visible'] ? 'true' : 'false';?>
    };
<?php
        if(array_key_exists('filter', $column) && array_key_exists('type', $column['filter'])) {
            $addFilterRow = true;
        }
    endforeach;
?>

<?php
    if(addFilterRow) :
        if($addActionColumn):
?>
    trFilter.append(jQuery('<th/>')); /* column for actions */
    filterParams[filterParams.length] = null;
<?php    
        endif;
    ?>
    bAddFilterRow = true;
    <?php    
        foreach($this->DataTable['columnsInfo'] as $key => $column) :
            $defText = '';
            $newElement = 'null';
            if(array_key_exists('filter', $column)) {
                if(array_key_exists('def_text', $column['filter'])) {
                    $defText = $column['filter']['def_text'];
                }
                if(array_key_exists('type', $column['filter'])) {
                    switch($column['filter']['type']) {
                        case 'text':
                            $newElement = "{'type': 'text'}";
                            break;
                        case 'select':
                            $values = '[]';
                            if(array_key_exists('values', $column['filter'])) {
                                if(!is_array($column['filter']['values'])) {
                                    $column['filter']['values'] = array($column['filter']['values']);
                                }
                                array_walk($column['filter']['values'], function (&$c){ $c = preg_replace("/'/", "/\\'/", $c); $c = "'".$c."'"; });
                                if(array_key_exists('use_keys', $column['filter']) && !empty($column['filter']['use_keys'])) {
                                    $vals = array();
                                    foreach($column['filter']['values'] as $key=>$value) {
                                        $vals[] = $key.': '.$value;
                                    }
                                    $values = sprintf("{%s}", join(",", $vals));
                                }
                                else {
                                    $values = sprintf("[%s]", join(",", $column['filter']['values']));
                                }
                            }
                            $newElement = "{'type': 'select', 'values' : ".$values."}";
                            break;
                    }
                }
            }
?>
    trFilter.append(jQuery('<th/>', {'text' : '<?php echo $defText; ?>'}));
    filterParams[filterParams.length] = <?php echo $newElement; ?>;
<?php
        endforeach;
    endif;
?>
    
    thead.append(trHeader);
    if(bAddFilterRow) {
        thead.append(trFilter);
    }
    $('#list_table').append(thead);


    var oCache = {
        'iCacheLower': -1
    };
         
    function fnSetKey( aoData, sKey, mValue )
    {
        for ( var i=0, iLen=aoData.length ; i<iLen ; i++ ) {
            if ( aoData[i].name == sKey ) {
                aoData[i].value = mValue;
            }
        }
    }
     
    function fnGetKey( aoData, sKey )
    {
        for ( var i=0, iLen=aoData.length ; i<iLen ; i++ ) {
            if ( aoData[i].name == sKey ) {
                return aoData[i].value;
            }
        }
        return null;
    }
     
    function fnDataTablesPipeline ( sSource, aoData, fnCallback )
    {
        var iPipe = 5; /* Ajust the pipe size */
         
        var bNeedServer = false;
        var sEcho = fnGetKey(aoData, "sEcho");
        var iRequestStart = fnGetKey(aoData, "iDisplayStart");
        var iRequestLength = parseInt(fnGetKey(aoData, "iDisplayLength"));
        var iRequestEnd = iRequestStart + iRequestLength;
        oCache.iDisplayStart = iRequestStart;
         
        /* outside pipeline? */
        if ( oCache.iCacheLower < 0 || iRequestStart < oCache.iCacheLower || iRequestEnd > oCache.iCacheUpper ) {
            bNeedServer = true;
        }
         
        /* sorting etc changed? */
        if ( oCache.lastRequest && !bNeedServer ) {
            for( var i=0, iLen=aoData.length ; i<iLen ; i++ ) {
                if ( aoData[i].name != "iDisplayStart" && aoData[i].name != "iDisplayLength" && aoData[i].name != "sEcho" ) {
                    if (undefined == oCache.lastRequest[i] || aoData[i].value != oCache.lastRequest[i].value ) {
                        bNeedServer = true;
                        break;
                    }
                }
            }
        }
         
        /* Store the request for checking next time around */
        oCache.lastRequest = aoData.slice();
         
        if ( bNeedServer ) {
            if ( iRequestStart < oCache.iCacheLower ) {
                iRequestStart = iRequestStart - (iRequestLength*(iPipe-1));
                if ( iRequestStart < 0 ) {
                    iRequestStart = 0;
                }
            }
             
            oCache.iCacheLower = iRequestStart;
            oCache.iCacheUpper = iRequestStart + (iRequestLength * iPipe);
            oCache.iDisplayLength = fnGetKey( aoData, "iDisplayLength" );
            fnSetKey( aoData, "iDisplayStart", iRequestStart );
            fnSetKey( aoData, "iDisplayLength", iRequestLength*iPipe );
             
            $.getJSON( sSource, aoData, function (json) {
                /* Callback processing */
                oCache.lastJson = jQuery.extend(true, {}, json);
                 
                if ( oCache.iCacheLower != oCache.iDisplayStart ) {
                    json.aaData.splice( 0, oCache.iDisplayStart-oCache.iCacheLower );
                }
                json.aaData.splice( oCache.iDisplayLength, json.aaData.length );
                 
                fnCallback(json)
            } );
        }
        else {
            json = jQuery.extend(true, {}, oCache.lastJson);
            json.sEcho = sEcho; /* Update the echo for each response */
            json.aaData.splice( 0, iRequestStart-oCache.iCacheLower );
            json.aaData.splice( iRequestLength, json.aaData.length );
            fnCallback(json);
            return;
        }
    }
             

    var defSortColumn = <?php echo array_key_exists('defSortColumn', $this->DataTable) ? $this->DataTable['defSortColumn'] : 1; ?>;
    var defSortDir = '<?php echo array_key_exists('defSortDir', $this->DataTable) ? $this->DataTable['defSortDir'] : 'desc'; ?>';
    var oTable = $('#list_table').dataTable( {
         'sPaginationType'  : 'full_numbers'
        ,'iDisplayLength'   : '50'
        ,'sDom'             : '<?php echo $sDom; ?>'
        ,'aaSorting'        : [[defSortColumn, defSortDir]]
        ,'bSortCellsTop'    : true
        ,'bProcessing'      : true
        ,'bServerSide'      : true
        ,'bServerMethod'    : 'POST'
        ,'sAjaxSource'      : '<?php echo $this->DataTable['serverUrl'];?>'
        ,'bDeferRender'     : true
        ,'fnServerData'     : fnDataTablesPipeline
        ,'fnServerParams'   : function ( aoData ) {
<?php
    if(array_key_exists('params', $this->DataTable)) :
        foreach($this->DataTable['params'] as $pName => $pValue) : 
?>            
            aoData.push({
                 'name' : '<?php echo $pName;?>'
                ,'value': '<?php echo $pValue;?>'
            });
<?php
        endforeach;
    endif;
?>            
        }
        ,'aoColumns'        : aoColumns
     
    });
    if(bAddFilterRow) {
        oTable.columnFilter({
             'sPlaceHolder' : 'head:after'
            ,'aoColumns'    : filterParams
        });
    }
    
<?php
    if(array_key_exists('toolbar', $this->DataTable)) : ?>
    var tContainer = $('<div id="list_toolbar_container"/>');
<?php    
        foreach($this->DataTable['toolbar'] as $toolAction) :
            $text = $toolAction['text'];
            $url = $toolAction['url']; 
?>
    tContainer.append('<a class="list_toolbar_action" href="<?php echo $url;?>"><?php echo $text;?></a>');
<?php  endforeach; ?>
    $('#list_toolbar').append(tContainer);
<?php endif; ?>            

    $(document).on('click', '#list_table tbody tr a.row_action', function () {
        var idPrefix = this.id;
        var url = $('#' + idPrefix + '_url', this).text();
        var message = $('#' + idPrefix + '_message', this).text();

        if(!message) {
            $(location).attr('href', url);
        }
        else {
            $("#dialog-confirm").html(message);
            $("#dialog-confirm").dialog({
                 modal: true
                ,dialogClass: 'alert'
                ,title: '<?php echo $this->translate(_("Warning"))?>'
                ,buttons: {
                    "OK": function() {
                        $(location).attr('href', url);
                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }
                }
            })
        }
    } );    
} );

</script>                 

<div id="dialog-confirm">
</div>

<div id="list_div">
</div>