<?php
    if(!isset($this->paginator_params)) {
        $this->paginator_params = array();
    }
?>
<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- First page link -->
<?php if ( 2 < $this->current): ?>
  <a href="<?php echo $this->url(array_merge($this->paginator_params, array('page' => $this->first))); ?>">&lt;&lt;</a> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array_merge($this->paginator_params, array('page' => $this->previous))); ?>">&lt;</a> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array_merge($this->paginator_params, array('page' => $page))); ?>"><?php echo $page; ?></a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array_merge($this->paginator_params, array('page' => $this->next))); ?>">&gt;</a>
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array_merge($this->paginator_params, array('page' => $this->last))); ?>">&gt;&gt;</a>
<?php endif; ?>

&nbsp;&nbsp;<?php echo $this->firstItemNumber; ?>-<?php echo $this->lastItemNumber; ?> / <?php echo $this->totalItemCount; ?>
</div>

<?php endif; ?>