insert into country(id, iso_3166, name) values(1, 'AF', 'Afganistan');
insert into country(id, iso_3166, name) values(2, 'AL', 'Albania');
insert into country(id, iso_3166, name) values(3, 'DZ', 'Algeria');
insert into country(id, iso_3166, name) values(4, 'AS', 'American Samoa');
insert into country(id, iso_3166, name) values(5, 'AD', 'Andorra');
insert into country(id, iso_3166, name) values(6, 'AO', 'Angola');
insert into country(id, iso_3166, name) values(7, 'AI', 'Anguilla');
insert into country(id, iso_3166, name) values(8, 'AQ', 'Antarctica');
insert into country(id, iso_3166, name) values(9, 'AG', 'Antigua And Barbuda');
insert into country(id, iso_3166, name) values(10, 'AR', 'Argentina');
insert into country(id, iso_3166, name) values(11, 'AM', 'Armenia');
insert into country(id, iso_3166, name) values(12, 'AW', 'Aruba');
insert into country(id, iso_3166, name) values(13, 'AU', 'Australia');
insert into country(id, iso_3166, name) values(14, 'AT', 'Austria');
insert into country(id, iso_3166, name) values(15, 'AZ', 'Azerbaijan');
insert into country(id, iso_3166, name) values(16, 'BS', 'Bahamas');
insert into country(id, iso_3166, name) values(17, 'BH', 'Bahrain');
insert into country(id, iso_3166, name) values(18, 'BD', 'Bangladesh');
insert into country(id, iso_3166, name) values(19, 'BB', 'Barbados');
insert into country(id, iso_3166, name) values(20, 'BY', 'Belarus');
insert into country(id, iso_3166, name) values(21, 'BE', 'Belgium');
insert into country(id, iso_3166, name) values(22, 'BZ', 'Belize');
insert into country(id, iso_3166, name) values(23, 'BJ', 'Benin');
insert into country(id, iso_3166, name) values(24, 'BM', 'Bermuda');
insert into country(id, iso_3166, name) values(25, 'BT', 'Bhutan');
insert into country(id, iso_3166, name) values(26, 'BO', 'Bolivia');
insert into country(id, iso_3166, name) values(27, 'BA', 'Bosnia and Herzegowina');
insert into country(id, iso_3166, name) values(28, 'BW', 'Botswana');
insert into country(id, iso_3166, name) values(30, 'BR', 'Brasil');
insert into country(id, iso_3166, name) values(31, 'IO', 'British-Virgin Islands');
insert into country(id, iso_3166, name) values(32, 'BN', 'Brunei Darussalam');
insert into country(id, iso_3166, name) values(33, 'BG', 'Bulgaria');
insert into country(id, iso_3166, name) values(34, 'BF', 'Burkina Faso');
insert into country(id, iso_3166, name) values(35, 'BI', 'Burundi');
insert into country(id, iso_3166, name) values(36, 'KH', 'Cambodia');
insert into country(id, iso_3166, name) values(37, 'CM', 'Cameroon');
insert into country(id, iso_3166, name) values(38, 'CA', 'Canada');
insert into country(id, iso_3166, name) values(39, 'CV', 'Cape Verde');
insert into country(id, iso_3166, name) values(40, 'KY', 'Cayman Islands');
insert into country(id, iso_3166, name) values(41, 'CF', 'Central African Republic');
insert into country(id, iso_3166, name) values(42, 'TD', 'Char');
insert into country(id, iso_3166, name) values(43, 'CL', 'Chile');
insert into country(id, iso_3166, name) values(44, 'CN', 'China');
insert into country(id, iso_3166, name) values(45, 'CX', 'Christmas Island');
insert into country(id, iso_3166, name) values(46, 'CC', 'Cocos Islands');
insert into country(id, iso_3166, name) values(47, 'CO', 'Colombia');
insert into country(id, iso_3166, name) values(48, 'KM', 'Comoros');
insert into country(id, iso_3166, name) values(49, 'CG', 'Congo');
insert into country(id, iso_3166, name) values(50, 'CD', 'The Democratic Republic Of The Congo');
insert into country(id, iso_3166, name) values(51, 'CK', 'Cooc Islands');
insert into country(id, iso_3166, name) values(52, 'CR', 'Costa Rica');
insert into country(id, iso_3166, name) values(53, 'CI', 'Cote D\'ivoire');
insert into country(id, iso_3166, name) values(54, 'HR', 'Croatia');
insert into country(id, iso_3166, name) values(55, 'CU', 'Cuba');
insert into country(id, iso_3166, name) values(56, 'CY', 'Cyprus');
insert into country(id, iso_3166, name) values(57, 'CZ', 'Czech Republic');
insert into country(id, iso_3166, name) values(58, 'DK', 'Denmark');
insert into country(id, iso_3166, name) values(59, 'DJ', 'Djibouti');
insert into country(id, iso_3166, name) values(60, 'DM', 'Dominica');
insert into country(id, iso_3166, name) values(61, 'DO', 'Dominican Republic');
insert into country(id, iso_3166, name) values(62, 'TP', 'East Timor');
insert into country(id, iso_3166, name) values(63, 'EC', 'Ecuador');
insert into country(id, iso_3166, name) values(64, 'EG', 'Egypt');
insert into country(id, iso_3166, name) values(65, 'SV', 'El Salvador');
insert into country(id, iso_3166, name) values(66, 'GQ', 'Equatorial Guinea');
insert into country(id, iso_3166, name) values(67, 'ER', 'Eritrea');
insert into country(id, iso_3166, name) values(68, 'EE', 'Estonia');
insert into country(id, iso_3166, name) values(69, 'ET', 'Ethiopia');
insert into country(id, iso_3166, name) values(70, 'FK', 'Falkland Islands');
insert into country(id, iso_3166, name) values(71, 'FO', 'Faroe Islands');
insert into country(id, iso_3166, name) values(72, 'FJ', 'Fiji');
insert into country(id, iso_3166, name) values(73, 'FI', 'Finland');
insert into country(id, iso_3166, name) values(74, 'FR', 'France');
insert into country(id, iso_3166, name) values(75, 'GF', 'French Guiana');
insert into country(id, iso_3166, name) values(76, 'PF', 'French Polynesia');
insert into country(id, iso_3166, name) values(77, 'TF', 'French Southern Territories');
insert into country(id, iso_3166, name) values(78, 'GA', 'Gabon');
insert into country(id, iso_3166, name) values(79, 'GM', 'Gambia');
insert into country(id, iso_3166, name) values(80, 'GE', 'Georgia');
insert into country(id, iso_3166, name) values(81, 'DE', 'Germany');
insert into country(id, iso_3166, name) values(82, 'GH', 'Ghana');
insert into country(id, iso_3166, name) values(83, 'GI', 'Gibraltar');
insert into country(id, iso_3166, name) values(84, 'GR', 'Greece');
insert into country(id, iso_3166, name) values(85, 'GL', 'Greenland');
insert into country(id, iso_3166, name) values(86, 'GD', 'Grenada');
insert into country(id, iso_3166, name) values(87, 'GP', 'Guadeloupe');
insert into country(id, iso_3166, name) values(88, 'GU', 'Guam');
insert into country(id, iso_3166, name) values(89, 'GT', 'Guatemala');
insert into country(id, iso_3166, name) values(90, 'GN', 'Guinea');
insert into country(id, iso_3166, name) values(91, 'GW', 'Guinea-Bissau');
insert into country(id, iso_3166, name) values(92, 'GY', 'Guyana');
insert into country(id, iso_3166, name) values(93, 'HT', 'Haiti');
insert into country(id, iso_3166, name) values(95, 'VA', 'Vatican');
insert into country(id, iso_3166, name) values(96, 'HN', 'Honduras');
insert into country(id, iso_3166, name) values(97, 'HK', 'Hong Kong');
insert into country(id, iso_3166, name) values(98, 'HU', 'Hungary');
insert into country(id, iso_3166, name) values(99, 'IS', 'Iceland');
insert into country(id, iso_3166, name) values(100, 'IN', 'India');
insert into country(id, iso_3166, name) values(101, 'ID', 'Indonesia');
insert into country(id, iso_3166, name) values(102, 'IR', 'Iran');
insert into country(id, iso_3166, name) values(103, 'IQ', 'Iraq');
insert into country(id, iso_3166, name) values(104, 'IE', 'Ireland');
insert into country(id, iso_3166, name) values(105, 'IL', 'Israel');
insert into country(id, iso_3166, name) values(106, 'IT', 'Italy');
insert into country(id, iso_3166, name) values(107, 'JM', 'Jamaica');
insert into country(id, iso_3166, name) values(108, 'JP', 'Japan');
insert into country(id, iso_3166, name) values(109, 'JO', 'Jordan');
insert into country(id, iso_3166, name) values(110, 'KZ', 'Kazakhstan');
insert into country(id, iso_3166, name) values(111, 'KE', 'Kenya');
insert into country(id, iso_3166, name) values(112, 'KI', 'Kiribati');
insert into country(id, iso_3166, name) values(113, 'KP', 'Democratic People\'s Republic Of Korea');
insert into country(id, iso_3166, name) values(114, 'KR', 'Republic Of Korea');
insert into country(id, iso_3166, name) values(115, 'KW', 'Kuwait');
insert into country(id, iso_3166, name) values(116, 'KG', 'Kyrgyzistan');
insert into country(id, iso_3166, name) values(117, 'LA', 'Laos');
insert into country(id, iso_3166, name) values(118, 'LV', 'Latvia');
insert into country(id, iso_3166, name) values(119, 'LB', 'Lebanon');
insert into country(id, iso_3166, name) values(120, 'LS', 'Lesotho');
insert into country(id, iso_3166, name) values(121, 'LR', 'Liberia');
insert into country(id, iso_3166, name) values(122, 'LY', 'Libya');
insert into country(id, iso_3166, name) values(123, 'LI', 'Liechtenstein');
insert into country(id, iso_3166, name) values(124, 'LT', 'Lithuania');
insert into country(id, iso_3166, name) values(125, 'LU', 'Luxembourg');
insert into country(id, iso_3166, name) values(126, 'MO', 'Macau');
insert into country(id, iso_3166, name) values(127, 'MK', 'The Former Yugoslav Republic Of Macedonia');
insert into country(id, iso_3166, name) values(128, 'MG', 'Madagaskar');
insert into country(id, iso_3166, name) values(129, 'MW', 'Malawi');
insert into country(id, iso_3166, name) values(130, 'MY', 'Malasia');
insert into country(id, iso_3166, name) values(131, 'MV', 'Maldives');
insert into country(id, iso_3166, name) values(132, 'ML', 'Mali');
insert into country(id, iso_3166, name) values(133, 'MT', 'Malta');
insert into country(id, iso_3166, name) values(134, 'MH', 'Marshall Islands');
insert into country(id, iso_3166, name) values(135, 'MQ', 'Martinique');
insert into country(id, iso_3166, name) values(136, 'MR', 'Mauritania');
insert into country(id, iso_3166, name) values(137, 'MU', 'Mauritius');
insert into country(id, iso_3166, name) values(138, 'YT', 'Mayotte');
insert into country(id, iso_3166, name) values(139, 'MX', 'Mexico');
insert into country(id, iso_3166, name) values(140, 'FM', 'Federated States Of Micronesia');
insert into country(id, iso_3166, name) values(141, 'MD', 'Republic Of Moldova');
insert into country(id, iso_3166, name) values(142, 'MC', 'Monaco');
insert into country(id, iso_3166, name) values(143, 'MN', 'Mongolia');
insert into country(id, iso_3166, name) values(144, 'MS', 'Montserrat');
insert into country(id, iso_3166, name) values(145, 'MA', 'Morocco');
insert into country(id, iso_3166, name) values(146, 'MZ', 'Mozambique');
insert into country(id, iso_3166, name) values(147, 'MM', 'Myanmar');
insert into country(id, iso_3166, name) values(148, 'NA', 'Namibia');
insert into country(id, iso_3166, name) values(149, 'NR', 'Nauru');
insert into country(id, iso_3166, name) values(150, 'NP', 'Nepal');
insert into country(id, iso_3166, name) values(151, 'NL', 'Netherlands');
insert into country(id, iso_3166, name) values(152, 'AN', 'Netherlands Antilles');
insert into country(id, iso_3166, name) values(153, 'NC', 'New Caledonia');
insert into country(id, iso_3166, name) values(154, 'NZ', 'New Zealand');
insert into country(id, iso_3166, name) values(155, 'NI', 'Nicaragua');
insert into country(id, iso_3166, name) values(156, 'NE', 'Niger');
insert into country(id, iso_3166, name) values(157, 'NG', 'Nigeria');
insert into country(id, iso_3166, name) values(158, 'NU', 'Niue');
insert into country(id, iso_3166, name) values(159, 'NF', 'Norfolk Islands');
insert into country(id, iso_3166, name) values(160, 'MP', 'Nothern Mariana Islands');
insert into country(id, iso_3166, name) values(161, 'NO', 'Norway');
insert into country(id, iso_3166, name) values(162, 'OM', 'Oman');
insert into country(id, iso_3166, name) values(163, 'PK', 'Pakistan');
insert into country(id, iso_3166, name) values(164, 'PW', 'Palau');
insert into country(id, iso_3166, name) values(165, 'PS', 'Palestinian Territory, Occupied');
insert into country(id, iso_3166, name) values(166, 'PA', 'Panama');
insert into country(id, iso_3166, name) values(167, 'PG', 'Papua New Guinea');
insert into country(id, iso_3166, name) values(168, 'PY', 'Paraguay');
insert into country(id, iso_3166, name) values(169, 'PE', 'Peru');
insert into country(id, iso_3166, name) values(170, 'PH', 'Philippines');
insert into country(id, iso_3166, name) values(171, 'PN', 'Pitcairn');
insert into country(id, iso_3166, name) values(172, 'PL', 'Poland');
insert into country(id, iso_3166, name) values(173, 'PT', 'Portugal');
insert into country(id, iso_3166, name) values(174, 'PR', 'Puerto Rico');
insert into country(id, iso_3166, name) values(175, 'QA', 'Quatar');
insert into country(id, iso_3166, name) values(176, 'RE', 'Reunion');
insert into country(id, iso_3166, name) values(177, 'RO', 'Romania');
insert into country(id, iso_3166, name) values(178, 'RU', 'Russian Federation');
insert into country(id, iso_3166, name) values(179, 'RW', 'Rwanda');
insert into country(id, iso_3166, name) values(180, 'SH', 'Saint Helena');
insert into country(id, iso_3166, name) values(181, 'KN', 'Saint Kitts And Navis');
insert into country(id, iso_3166, name) values(182, 'LC', 'Saint Lucia');
insert into country(id, iso_3166, name) values(183, 'PM', 'Saint Pierre And Miquelon');
insert into country(id, iso_3166, name) values(184, 'VC', 'Saint Vincent And Grenadines');
insert into country(id, iso_3166, name) values(185, 'WS', 'Samoa');
insert into country(id, iso_3166, name) values(186, 'SM', 'San Marino');
insert into country(id, iso_3166, name) values(187, 'ST', 'Sao Tome e Principe');
insert into country(id, iso_3166, name) values(188, 'SA', 'Saudi Arabia');
insert into country(id, iso_3166, name) values(189, 'SN', 'Senegal');
insert into country(id, iso_3166, name) values(190, 'SC', 'Seychelles');
insert into country(id, iso_3166, name) values(191, 'SL', 'Sierra Leone');
insert into country(id, iso_3166, name) values(192, 'SG', 'Singapore');
insert into country(id, iso_3166, name) values(193, 'SK', 'Slovakia');
insert into country(id, iso_3166, name) values(194, 'SI', 'Slovenia');
insert into country(id, iso_3166, name) values(195, 'SB', 'Solomon Islands');
insert into country(id, iso_3166, name) values(196, 'SO', 'Somalia');
insert into country(id, iso_3166, name) values(197, 'ZA', 'South Africa');
insert into country(id, iso_3166, name) values(198, 'GS', 'Falkland Islands');
insert into country(id, iso_3166, name) values(199, 'ES', 'Spain');
insert into country(id, iso_3166, name) values(200, 'LK', 'Sri Lanka');
insert into country(id, iso_3166, name) values(201, 'SD', 'Sudan');
insert into country(id, iso_3166, name) values(202, 'SR', 'Suriname');
insert into country(id, iso_3166, name) values(203, 'SJ', 'Svalbard and Jan Mayen Islands');
insert into country(id, iso_3166, name) values(204, 'SZ', 'Swaziland');
insert into country(id, iso_3166, name) values(205, 'SE', 'Sweden');
insert into country(id, iso_3166, name) values(206, 'CH', 'Switzerland');
insert into country(id, iso_3166, name) values(207, 'SY', 'Syrian Arab Republic');
insert into country(id, iso_3166, name) values(208, 'TW', 'Taiwan, Province Of China');
insert into country(id, iso_3166, name) values(209, 'TJ', 'Tajikistan');
insert into country(id, iso_3166, name) values(210, 'TZ', 'United Republic Of Tanzania');
insert into country(id, iso_3166, name) values(211, 'TH', 'Thailand');
insert into country(id, iso_3166, name) values(212, 'TG', 'Togo');
insert into country(id, iso_3166, name) values(213, 'TK', 'Tokelau');
insert into country(id, iso_3166, name) values(214, 'TO', 'Tonga');
insert into country(id, iso_3166, name) values(215, 'TT', 'Trinidad And Tobago');
insert into country(id, iso_3166, name) values(216, 'TN', 'Tunisia');
insert into country(id, iso_3166, name) values(217, 'TR', 'Turkey');
insert into country(id, iso_3166, name) values(218, 'TM', 'Turkmenistan');
insert into country(id, iso_3166, name) values(219, 'TC', 'Turks And Cacois Islands');
insert into country(id, iso_3166, name) values(220, 'TV', 'Tuvalu');
insert into country(id, iso_3166, name) values(221, 'UG', 'Uganda');
insert into country(id, iso_3166, name) values(222, 'UA', 'Ukraine');
insert into country(id, iso_3166, name) values(223, 'AE', 'United Arab Emirates');
insert into country(id, iso_3166, name) values(224, 'GB', 'United Kingdom');
insert into country(id, iso_3166, name) values(225, 'US', 'United States');
insert into country(id, iso_3166, name) values(226, 'UM', 'United States Minor Outlying Islands');
insert into country(id, iso_3166, name) values(227, 'UY', 'Uruguay');
insert into country(id, iso_3166, name) values(228, 'UZ', 'Uzbekistan');
insert into country(id, iso_3166, name) values(229, 'VU', 'Vanuatu');
insert into country(id, iso_3166, name) values(230, 'VE', 'Venezuela');
insert into country(id, iso_3166, name) values(231, 'VN', 'Viet Nam');
insert into country(id, iso_3166, name) values(232, 'VG', 'Virgin Islands, British');
insert into country(id, iso_3166, name) values(233, 'VI', 'Virgin Islands, U.S.');
insert into country(id, iso_3166, name) values(234, 'WF', 'Wallis and Futuna');
insert into country(id, iso_3166, name) values(235, 'EH', 'Western Sahara');
insert into country(id, iso_3166, name) values(236, 'YE', 'Yemen');
insert into country(id, iso_3166, name) values(238, 'ZM', 'Zambia');
insert into country(id, iso_3166, name) values(239, 'ZW', 'Zimbabwe');
insert into country(id, iso_3166, name) values(240, 'ME', 'Montenegro');
insert into country(id, iso_3166, name) values(241, 'RS', 'Serbia');
