<?php
$this->headScript()->appendFile('/js/jquery/plugin/showLoading/jquery.showLoading.min.js');
$this->headLink()->appendStylesheet('/css/showLoading.css');

$textForEmptyAdrStopDate = $this->translate(_("Ongoing"));
?>
<style type="text/css" title="currentStyle">
a {
    cursor: pointer;
    text-decoration: underline;
}
</style>

<script type="text/javascript" charset="utf-8">
	var g_selectedPatient = '<?php echo $this->id_patient?>';
	var g_dictEntities = new Array();
<?php foreach($this->dictEntities as $key=>$values) :?>
    g_dictEntities[<?php echo $key;?>] = [<?php echo join(" , ", $values);?>];
<?php endforeach; ?>
	
	function patientsReload(){
		if($("#id_patient option").length) {
			g_selectedPatient = $("#id_patient option:selected").val();
		}
  	    $.ajax({
	        url:'<?php echo $this->url(array('controller' => 'patient', "action" => "load-array-of-active")); ?>'
	        ,type:'POST'
	        ,data:''
	        ,success: function(data){
	            if(!data || !data.success) {
	                return;
	            }

	            var select = $('#id_patient');
	            if(select.prop) {
	                var options = select.prop('options');
	            }
	            else {
	                var options = select.attr('options');
	            }
	            $('option', select).remove();
                options[options.length] = new Option('', '');
	            for (var key in data.rows){
		            var selectedFlag = false;
		            if(key == g_selectedPatient) {
			            selectedFlag = true;
		            }
	                options[options.length] = new Option(data.rows[key], key, selectedFlag);
	            }
	        }
	        ,complete: function(jqXHR, textStatus) {
	        }
	  });
	}

	function dictEntitiesReload(ctrlId, dictTypeId){
		if($(ctrlId + " option").length) {
			g_dictEntities[dictTypeId] = new Array();
			$(ctrlId + " option:selected").each( function() {
                g_dictEntities[dictTypeId][g_dictEntities[dictTypeId].length] = parseInt($(this).val(), 10);
            });
		}
  	    $.ajax({
	        url:'<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "load-array-for-type")); ?>'
	        ,type:'POST'
	        ,data: {
		        type_id: dictTypeId
		    }
	        ,success: function(data){
	            if(!data || !data.success) {
	                return;
	            }

	            var select = $(ctrlId);
	            if(select.prop) {
	                var options = select.prop('options');
	            }
	            else {
	                var options = select.attr('options');
	            }
	            $('option', select).remove();
	            for (var key in data.rows){
		            var selectedFlag = false;
		            if(-1 != jQuery.inArray(parseInt(key, 10), g_dictEntities[dictTypeId])) { /* to check int with int */
			            selectedFlag = true;
		            }
	                options[options.length] = new Option(data.rows[key], key, selectedFlag);
	            }
	        }
	        ,complete: function(jqXHR, textStatus) {
	        }
	  });
	}
	
	function linkFormToDlg(dialogId) {
    	var form = $(dialogId + '>form');
    	if(form) {
	    	form.submit(function(event) {
    	        event.preventDefault();
    	        $(dialogId).showLoading();
    	        $.ajax( {
    	             type: "POST"
    	            ,url: $(this).attr('action')
      	            ,data: $(this).serialize()
    	            ,success: function(response) {
    	        	    $(dialogId).html(response);
    	        	    linkFormToDlg(dialogId);
    	            }
	    	        ,complete: function(jqXHR, textStatus) {
	    	            $(dialogId).hideLoading();
	    	        }
    	        });			    	      
    	    });
    	} 			    	  
	}


	function checkIsReferredIn()
	{
		if(0 == $('input:radio[name=is_referred_in]:checked').val()) {
			$('#row_referred_in').hide();
		}
		else {
			$('#row_referred_in').show();
		}
	}

	function checkIsReferredOut()
	{
		if(0 == $('input:radio[name=is_referred_out]:checked').val()) {
			$('#row_referred_out').hide();
		}
		else {
			$('#row_referred_out').show();
		}
	}

	function checkIsHtcDone()
	{
		if(0 == $('input:radio[name=is_htc_done]:checked').val()) {
			$('#row_htc_result_id').hide();
		}
		else {
			$('#row_htc_result_id').show();
		}
	}


	
    function updateErrorInfo(dlgId, message) {
	    var infoEl = $(dlgId + " .errorInfo");
	    if('' != message) {
	        infoEl.text(message).addClass("ui-state-highlight");
	    }
	    else {
	        infoEl.text('').removeClass("ui-state-highlight");
	    }
	      
	    setTimeout(function() {
	        infoEl.removeClass("ui-state-highlight", 1500);
	    }, 500 );
	}

    
    function cleanErrorInfo(dlgId) {
        updateErrorInfo(dlgId, '');
        $('#add-dict-entity-name').val("").removeClass("ui-state-error");
    }

	$(document).ready(function() {
    	$('#main_form').submit(function() {
        	if(!$("#id_patient option:selected").val()) {
            	alert('<?php echo $this->translate(_("Necessary to choose patient"));?>');
            	$("#id_patient").focus();
            	return false;
        	}
        	if(!$('#date_of_visit').val()) {
            	alert('<?php echo $this->translate(_("Necessary to enter date of visit"));?>');
            	$("#date_of_visit").focus();
            	return false;
        	}
        	if('<?php echo $textForEmptyAdrStopDate?>' == $('#adr_stop_date').val()) {
        		$('#adr_stop_date').val('');
        	}
        	return true;
	    });
		
	    patientsReload();
	    dictEntitiesReload('#referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    dictEntitiesReload('#referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    dictEntitiesReload('#htc_result_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_HTC_RESULT;?>');
	    
	    var newPatientDlg = $("<div id='dialog-add-patient'></div>").dialog({
			     dialogClass: 'dialog-content'
				,title: '<?php echo $this->translate(_("Add Patient"));?>'
			    ,autoOpen: false
		    	,height: 500
			    ,width: 500
			    ,modal: true
			    ,close: function() {
				    patientsReload();
			    }
        });

	    $("#dlg-add-dict-entity").dialog({
	        dialogClass: 'dialog-content'
	        ,autoOpen: false
	        ,height: 200
	        ,width: 300
	        ,modal: true
	        ,buttons: {
	            '<?php echo $this->translate(_("Add"));?>': function() {
                    var name = $('#add-dict-entity-name');
	                if(!name.val()) {
	                  name.addClass("ui-state-error");
	                  updateErrorInfo('#dlg-add-dict-entity', '<?php echo $this->translate(_("Necessary to enter value"));?>');
	                  return false;
	                }
	                var type_id = $(this).attr('type_id');
	                var list_element_id = $(this).attr('list_element_id');
	            
	    	        $('#dlg-add-dict-entity').showLoading();
 	                $.ajax({
	                     url: '<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "create-ajax")); ?>'
	                    ,type:'POST'
	              	    ,data: {
	                         name : name.val()
	                        ,type_id: type_id
	                    }
		                ,success: function(data) {
		                    if (data && data.success){
		                    	$('#dlg-add-dict-entity').dialog("close");
	    	            	    dictEntitiesReload('#'+list_element_id, type_id);
	            	        }
	                	    else{
	                    	    var errorMsg = '<?php echo $this->translate(_("Internal Error"));?>';
	                      	    if(data) {
	                          	    errorMsg = data.error;
	                            }
	                            updateErrorInfo('#dlg-add-dict-entity', errorMsg);
	                        }
	                    }
		    	        ,complete: function(jqXHR, textStatus) {
		    	        	$('#dlg-add-dict-entity').hideLoading();
		    	        }
	                });
	          }
	          ,'<?php echo $this->translate(_("Cancel"));?>': function() {
	              $(this).dialog("close");
	          }
	        }
	        ,close: function() {
	        }
	        ,open: function() {
	            cleanErrorInfo('#dlg-add-dict-entity');
	        }
	      });
        
/***   START OnClick events ***/		
	    $("#link-add-patient").click(function() {
	    	newPatientDlg.load('<?php echo $this->url(array("controller" => "patient", "action" => "create", "for_dialog" => 1)); ?>', function(){
		    	linkFormToDlg("#dialog-add-patient");
		    }).dialog('open');
	        return false;
	    });
	    $("#link-add-referred_in").click(function() {
	    	$("#dlg-add-dict-entity").attr('type_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    	$("#dlg-add-dict-entity").attr('list_element_id', 'referred_in');
	    	$("#dlg-add-dict-entity").dialog('open');
	        return false;
	    });
	    $("#link-add-referred_out").click(function() {
	    	$("#dlg-add-dict-entity").attr('type_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    	$("#dlg-add-dict-entity").attr('list_element_id', 'referred_out');
	    	$("#dlg-add-dict-entity").dialog('open');
	        return false;
	    });
/***   END OnClick events ***/		

/*** START Bind of OnChange ***/        
        $('input[name = "is_referred_in"]').bind('change', function(){
            checkIsReferredIn();
        });
        $('input[name = "is_referred_out"]').bind('change', function(){
            checkIsReferredOut();
        });
        $('input[name = "is_htc_done"]').bind('change', function(){
            checkIsHtcDone();
        });
/*** END Bind of OnChange ***/        
        
        checkIsReferredIn();
        checkIsReferredOut();
        checkIsHtcDone();
        
        $("#date_of_visit").datepicker({dateFormat : 'yy-mm-dd', appendText: "(yyyy-mm-dd)"});
});
</script>	


<?php if(!empty($this->error)) : ?>
<div class="form_errors"><?php echo $this->error;?></div>
<?php endif;?>
<form id="main_form" class="zend_form" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('action' => 'create', 'type' => $this->type));?>">
<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="required"><label for="patient"><?php echo $this->translate(_("Patient"));?></label></div></td>
   <td>
     <select name="id_patient" id="id_patient">
     </select>&nbsp;
<?php if ($this->allow_create_patient) : ?>
     <a id="link-add-patient" href="#"><?php echo $this->translate(_("Add Patient"));?></a>
<?php endif;?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><label for="date_of_visit"><?php echo $this->translate(_("Date of Visit"));?></label></div></td>
   <td>
     <input type="text" name="date_of_visit" id="date_of_visit" value="<?php echo $this->dateOfVisit;?>">     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Referral Services Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_in"><?php echo $this->translate(_("Referred in?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_in" id="is_referred_in_0" value="0" <?php if(!$this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_in" id="is_referred_in_1" value="1" <?php if($this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_in">
   <td></td>
   <td>
     <select name="referred_in[]" id="referred_in" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_in"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_out"><?php echo $this->translate(_("Referred out?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_out" id="is_referred_out_0" value="0" <?php if(!$this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_out" id="is_referred_out_1" value="1" <?php if($this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_out">
   <td></td>
   <td>
     <select name="referred_out[]" id="referred_out" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_out"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referral_completed"><?php echo $this->translate(_("Was the referral completed?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referral_completed" id="is_referral_completed_0" value="0" <?php if(!$this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referral_completed" id="is_referral_completed_1" value="1" <?php if($this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_hiv_risk_assesment_done"><?php echo $this->translate(_("HIV risk assessment & counseling done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_0" value="0" <?php if(!$this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_1" value="1" <?php if($this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("HCT Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done"><?php echo $this->translate(_("HIV Testing done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done" id="is_htc_done_0" value="0" <?php if(!$this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done" id="is_htc_done_1" value="1" <?php if($this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_htc_result_id">
   <td></td>
   <td>
     <select name="htc_result_id" id="htc_result_id">
     </select>&nbsp;
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_client_received_htc"><?php echo $this->translate(_("Was the client Counseled, Tested & received results?"));?></label></div></td>
   <td>
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_0" value="0" <?php if(!$this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_1" value="1" <?php if($this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done_in_current_pharmacy"><?php echo $this->translate(_("Was the HCT done in your Pharmacy?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_0" value="0" <?php if(!$this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_1" value="1" <?php if($this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>


<input type="submit" name="save" value="<?php echo $this->translate(_("Save"));?>"/>     
</form>


<div id="dlg-add-dict-entity" title="<?php echo $this->translate(_("Add"));?>" type_id="" list_element_id="">
  <p class="errorInfo"></p>
  <form>
    <label for="name"><?php echo $this->translate(_("Name"));?></label>
    <input type="text" name="name" id="add-dict-entity-name" class="text ui-widget-content ui-corner-all" />
  </form>
</div>
