<?php
$this->headScript()->appendFile('/js/jquery/plugin/showLoading/jquery.showLoading.min.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.ui.position.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.contextMenu.js');

$this->headLink()->appendStylesheet('/css/showLoading.css');
$this->headLink()->appendStylesheet('/js/jquery/plugin/contextMenu/jquery.contextMenu.css');

$textForEmptyAdrStopDate = $this->translate(_("Ongoing"));
?>
<style type="text/css" title="currentStyle">
a {
    cursor: pointer;
    text-decoration: underline;
}
</style>

<script type="text/javascript" charset="utf-8">
var g_selectedPharmacy = '<?php echo $this->idPharmacy?>';
var g_dictEntities = new Array();
<?php foreach($this->dictEntities as $key=>$values) :?>
    g_dictEntities[<?php echo $key;?>] = [<?php if(is_array($values)) echo join(" , ", $values);?>];
<?php endforeach; ?>

    function pharmacyReload(){
        if($("#id_pharmacy option").length) {
            g_selectedPharmacy = $("#id_pharmacy option:selected").val();
        }
        $.ajax({
            url:'<?php echo $this->url(array('controller' => 'pharmacy', "action" => "load-array-of-active")); ?>'
            ,type:'POST'
            ,data:''
            ,success: function(data){
                if(!data || !data.success) {
                    return;
                    }

                var select = $('#id_pharmacy');
                if(select.prop) {
                    var options = select.prop('options');
                }
                else {
                    var options = select.attr('options');
                }
                $('option', select).remove();
                options[options.length] = new Option('', '');
                for (var key in data.rows){
                    var selectedFlag = false;
                    if(key == g_selectedPharmacy) {
                        selectedFlag = true;
                    } 
                    options[options.length] = new Option(data.rows[key], key, selectedFlag);
                }
            }
            ,complete: function(jqXHR, textStatus) {
            }
        });
    }

	function dictEntitiesReload(ctrlId, dictTypeId){
		if($(ctrlId + " option").length) {
			g_dictEntities[dictTypeId] = new Array();
			$(ctrlId + " option:selected").each( function() {
                g_dictEntities[dictTypeId][g_dictEntities[dictTypeId].length] = parseInt($(this).val(), 10);
            });
		}
  	    $.ajax({
	        url:'<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "load-array-for-type")); ?>'
	        ,type:'POST'
	        ,data: {
		        type_id: dictTypeId
		    }
	        ,success: function(data){
	            if(!data || !data.success) {
	                return;
	            }

	            var select = $(ctrlId);
	            if(select.prop) {
	                var options = select.prop('options');
	            }
	            else {
	                var options = select.attr('options');
	            }
	            $('option', select).remove();
	            for (var key in data.rows){
		            var selectedFlag = false;
		            if(-1 != jQuery.inArray(parseInt(key, 10), g_dictEntities[dictTypeId])) { /* to check int with int */
			            selectedFlag = true;
		            }
	                options[options.length] = new Option(data.rows[key], key, selectedFlag);
	            }
	        }
	        ,complete: function(jqXHR, textStatus) {
	        }
	  });
	}
	
	function linkFormToDlg(dialogId) {
    	var form = $(dialogId + '>form');
    	if(form) {
	    	form.submit(function(event) {
    	        event.preventDefault();
    	        $(dialogId).showLoading();
    	        $.ajax( {
    	             type: "POST"
    	            ,url: $(this).attr('action')
      	            ,data: $(this).serialize()
    	            ,success: function(response) {
    	        	    $(dialogId).html(response);
    	        	    linkFormToDlg(dialogId);
    	            }
	    	        ,complete: function(jqXHR, textStatus) {
	    	            $(dialogId).hideLoading();
	    	        }
    	        });			    	      
    	    });
    	} 			    	  
	}


	function checkIsReferredIn()
	{
		if(0 == $('input:radio[name=is_referred_in]:checked').val()) {
			$('#row_referred_in').hide();
		}
		else {
			$('#row_referred_in').show();
		}
	}

	function checkIsReferredOut()
	{
		if(0 == $('input:radio[name=is_referred_out]:checked').val()) {
			$('#row_referred_out').hide();
		}
		else {
			$('#row_referred_out').show();
		}
	}

	function checkIsHtcDone()
	{
		if(0 == $('input:radio[name=is_htc_done]:checked').val()) {
			$('#row_htc_result_id').hide();
		}
		else {
			$('#row_htc_result_id').show();
		}
	}

	function checkIsPalliativeServicesToPlwha()
	{
		if(0 == $('input:radio[name=is_palliative_services_to_plwha]:checked').val()) {
			$('#row_palliative_care_type').hide();
		}
		else {
			$('#row_palliative_care_type').show();
		}
	}

	function checkIsStiServices()
	{
		if(0 == $('input:radio[name=is_sti_services]:checked').val()) {
			$('#row_sti_type').hide();
		}
		else {
			$('#row_sti_type').show();
		}
	}
	
	function checkIsReproductiveHealthServices()
	{
		if(0 == $('input:radio[name=is_reproductive_health_services]:checked').val()) {
			$('#row_reproductive_health_type').hide();
		}
		else {
			$('#row_reproductive_health_type').show();
		}
	}

	function checkIsTuberculosisServices()
	{
		if(0 == $('input:radio[name=is_tuberculosis_services]:checked').val()) {
			$('#row_tuberculosis_type').hide();
		}
		else {
			$('#row_tuberculosis_type').show();
		}
	}

	function checkIsOvcServices()
	{
		if(0 == $('input:radio[name=is_ovc_services]:checked').val()) {
			$('#row_ovc_type').hide();
		}
		else {
			$('#row_ovc_type').show();
		}
	}

	
    function updateErrorInfo(dlgId, message) {
	    var infoEl = $(dlgId + " .errorInfo");
	    if('' != message) {
	        infoEl.text(message).addClass("ui-state-highlight");
	    }
	    else {
	        infoEl.text('').removeClass("ui-state-highlight");
	    }
	      
	    setTimeout(function() {
	        infoEl.removeClass("ui-state-highlight", 1500);
	    }, 500 );
	}

    
    function cleanErrorInfo(dlgId) {
        updateErrorInfo(dlgId, '');
        $('#add-dict-entity-name').val("").removeClass("ui-state-error");
    }


    function processPharmDictContextMenuPressed(key, options, list_element_id, type_id)
    {
        var label = options.$trigger[0].label;
        var value = options.$trigger[0].value;

        if('edit' == key) {
	    	$("#dlg-edit-dict-entity").attr('type_id', type_id);
	    	$("#dlg-edit-dict-entity").attr('list_element_id', list_element_id);
	    	$("#edit-dict-entity-name").val(label)
	    	$("#edit-dict-entity-id").val(value)
	    	$("#dlg-edit-dict-entity").dialog('open');
        }
        else if('delete' == key) {
	    	$("#dlg-remove-dict-entity").attr('dict_id', value);
	        $("#dlg-remove-dict-entity").attr('type_id', type_id);
	    	$("#dlg-remove-dict-entity").attr('list_element_id', list_element_id);
	        $('#remove-dict-entity-name').html(label);
        	$("#dlg-remove-dict-entity").dialog({
                modal: true
               ,dialogClass: 'alert'
               ,title: '<?php echo $this->translate(_("Warning"))?>'
               ,width: 450
               ,buttons: {
                   "OK": function() {
   	                    var type_id = $(this).attr('type_id');
   	                    var list_element_id = $(this).attr('list_element_id');
   	                    var dict_id = $(this).attr('dict_id');
   	                    
   	    	            $('#dlg-remove-dict-entity').showLoading();
  	                    $.ajax({
                            url: '<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "remove-ajax")); ?>'
                            ,type:'POST'
              	            ,data: {
                                id : dict_id
                            }
	                        ,success: function(data) {
	                            if (data && data.success){
	                    	        $('#dlg-remove-dict-entity').dialog("close");
    	            	            dictEntitiesReload('#'+list_element_id, type_id);
            	                }
                	            else {
                    	            var errorMsg = '<?php echo $this->translate(_("Internal Error"));?>';
                      	            if(data) {
                          	            errorMsg = data.error;
                                    }
                                    updateErrorInfo('#dlg-remove-dict-entity', errorMsg);
                                }
                            }
	    	                ,complete: function(jqXHR, textStatus) {
	    	        	        $('#dlg-remove-dict-entity').hideLoading();
	    	                }
                        });
                   },
                   Cancel: function() {
                       $(this).dialog("close");
                   }
               }
	           ,close: function() {
	           }
	           ,open: function() {
	               cleanErrorInfo('#dlg-remove-dict-entity');
	           }
           });
       }
    }

    function linkDynamicActionsToPharmDictCtrl(list_element_id, type_id)
    {
	    $("#link-add-"+list_element_id).click(function() {
	    	$("#dlg-add-dict-entity").attr('type_id', type_id);
	    	$("#dlg-add-dict-entity").attr('list_element_id', list_element_id);
	    	$("#dlg-add-dict-entity").dialog('open');
	        return false;
	    });
        $('#'+list_element_id).contextMenu({
            selector: 'option', 
            callback: function(key, options) {
                processPharmDictContextMenuPressed(key, options, list_element_id, type_id);
            },
            items: {
                "edit": {name: "Edit"},
                "delete": {name: "Delete"},
            }
        });
    }

    $(document).ready(function() {
    	$('#main_form').submit(function() {
        	if(!$("#id_pharmacy option:selected").val()) {
            	alert('<?php echo $this->translate(_("Necessary to choose pharmacy"));?>');
            	$("#id_pharmacy").focus();
            	return false;
        	}
        	if(!$("#patient_name").val()) {
            	alert('<?php echo $this->translate(_("Necessary to choose patient"));?>');
            	$("#patient_name").focus();
            	return false;
        	}
        	if($("#patient_name").val() && !$("#id_patient").val()) {
            	alert('<?php echo $this->translate(_("Unknown patient"));?>');
            	$("#patient_name").focus();
            	return false;
        	}
        	if(!$('#date_of_visit').val()) {
            	alert('<?php echo $this->translate(_("Necessary to enter date of visit"));?>');
            	$("#date_of_visit").focus();
            	return false;
        	}
        	if('<?php echo $textForEmptyAdrStopDate?>' == $('#adr_stop_date').val()) {
        		$('#adr_stop_date').val('');
        	}
        	return true;
	    });

        $("#patient_name").autocomplete({
        	source:     '<?php echo $this->url(array('controller' => 'patient', "action" => "load-array-of-active")); ?>'
        	,delay:     300
        	,focus: function(event, ui ) {
        		$("#patient_name").val(ui.item.label);
        		return false;
            }
        	,select: function( event, ui ) {
        		$("#patient_name").val(ui.item.label);
        		$("#id_patient").val(ui.item.value);
        		return false;
        	}
        });
	    
	    dictEntitiesReload('#referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    dictEntitiesReload('#referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    dictEntitiesReload('#htc_result_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_HTC_RESULT;?>');
	    dictEntitiesReload('#palliative_care_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_PALLIATIVE_CARE_TYPE;?>');
	    dictEntitiesReload('#sti_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_STI_TYPE;?>');
	    dictEntitiesReload('#reproductive_health_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REPRODUCTIVE_HEALTH_TYPE;?>');
	    dictEntitiesReload('#tuberculosis_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_TUBERCULOSIS_TYPE;?>');
	    dictEntitiesReload('#ovc_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_OVC_TYPE;?>');
	    
	    var newPharmacyDlg = $("<div id='dialog-add-pharmacy'></div>").dialog({
		     dialogClass: 'dialog-content'
			,title: '<?php echo $this->translate(_("Add Pharmacy"));?>'
		    ,autoOpen: false
	    	,height: 500
		    ,width: 700
		    ,modal: true
		    ,close: function() {
			    pharmacyReload();
		    }
	    });

	    var newPatientDlg = $("<div id='dialog-add-patient'></div>").dialog({
			     dialogClass: 'dialog-content'
				,title: '<?php echo $this->translate(_("Add Patient"));?>'
			    ,autoOpen: false
		    	,height: 500
			    ,width: 500
			    ,modal: true
        });

        $("#dlg-add-dict-entity").dialog({
	        dialogClass: 'dialog-content'
	        ,autoOpen: false
	        ,height: 200
	        ,width: 530
	        ,modal: true
	        ,buttons: {
	            '<?php echo $this->translate(_("Add"));?>': function() {
                    var name = $('#add-dict-entity-name');
	                if(!name.val()) {
	                  name.addClass("ui-state-error");
	                  updateErrorInfo('#dlg-add-dict-entity', '<?php echo $this->translate(_("Necessary to enter value"));?>');
	                  return false;
	                }
	                var type_id = $(this).attr('type_id');
	                var list_element_id = $(this).attr('list_element_id');
	            
	    	        $('#dlg-add-dict-entity').showLoading();
 	                $.ajax({
	                     url: '<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "create-ajax")); ?>'
	                    ,type:'POST'
	              	    ,data: {
	                         name : name.val()
	                        ,type_id: type_id
	                    }
		                ,success: function(data) {
		                    if (data && data.success){
		                    	$('#dlg-add-dict-entity').dialog("close");
	    	            	    dictEntitiesReload('#'+list_element_id, type_id);
	            	        }
	                	    else{
	                    	    var errorMsg = '<?php echo $this->translate(_("Internal Error"));?>';
	                      	    if(data) {
	                          	    errorMsg = data.error;
	                            }
	                            updateErrorInfo('#dlg-add-dict-entity', errorMsg);
	                        }
	                    }
		    	        ,complete: function(jqXHR, textStatus) {
		    	        	$('#dlg-add-dict-entity').hideLoading();
		    	        }
	                });
	          }
	          ,'<?php echo $this->translate(_("Cancel"));?>': function() {
	              $(this).dialog("close");
	          }
	        }
	        ,close: function() {
	        }
	        ,open: function() {
	            cleanErrorInfo('#dlg-add-dict-entity');
	        }
	    });

        $("#dlg-edit-dict-entity").dialog({
	        dialogClass: 'dialog-content'
	        ,autoOpen: false
	        ,height: 200
	        ,width: 530
	        ,modal: true
	        ,buttons: {
	            '<?php echo $this->translate(_("Save"));?>': function() {
                    var name = $('#edit-dict-entity-name');
	                if(!name.val()) {
	                    name.addClass("ui-state-error");
	                    updateErrorInfo('#dlg-edit-dict-entity', '<?php echo $this->translate(_("Necessary to enter value"));?>');
	                    return false;
	                }
                    var id = $('#edit-dict-entity-id');
	                var type_id = $(this).attr('type_id');
	                var list_element_id = $(this).attr('list_element_id');
	            
	    	        $('#dlg-edit-dict-entity').showLoading();
 	                $.ajax({
	                     url: '<?php echo $this->url(array('controller' => 'pharm-dict', "action" => "change-ajax")); ?>'
	                    ,type:'POST'
	              	    ,data: {
	                         name : name.val()
	                        ,id: id.val()
	                    }
		                ,success: function(data) {
		                    if (data && data.success){
		                    	$('#dlg-edit-dict-entity').dialog("close");
	    	            	    dictEntitiesReload('#'+list_element_id, type_id);
	            	        }
	                	    else{
	                    	    var errorMsg = '<?php echo $this->translate(_("Internal Error"));?>';
	                      	    if(data) {
	                          	    errorMsg = data.error;
	                            }
	                            updateErrorInfo('#dlg-edit-dict-entity', errorMsg);
	                        }
	                    }
		    	        ,complete: function(jqXHR, textStatus) {
		    	        	$('#dlg-edit-dict-entity').hideLoading();
		    	        }
	                });
	          }
	          ,'<?php echo $this->translate(_("Cancel"));?>': function() {
	              $(this).dialog("close");
	          }
	        }
	        ,close: function() {
	        }
	        ,open: function() {
	            cleanErrorInfo('#dlg-edit-dict-entity');
	        }
	    });
	    
        /***   START OnClick events ***/		
	    $("#link-add-patient").click(function() {
	    	newPatientDlg.load('<?php echo $this->url(array("controller" => "patient", "action" => "create", "for_dialog" => 1)); ?>', function(){
		    	linkFormToDlg("#dialog-add-patient");
		    }).dialog('open');
	        return false;
	    });
	    $("#link-add-pharmacy").click(function() {
	    	newPharmacyDlg.load('<?php echo $this->url(array("controller" => "pharmacy", "action" => "create", "for_dialog" => 1)); ?>', function(){
		    	linkFormToDlg("#dialog-add-pharmacy");
		    }).dialog('open');
	        return false;
	    });
/***   END OnClick events ***/		
	    
	    linkDynamicActionsToPharmDictCtrl('referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
	    linkDynamicActionsToPharmDictCtrl('referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
	    linkDynamicActionsToPharmDictCtrl('palliative_care_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_PALLIATIVE_CARE_TYPE;?>');
	    linkDynamicActionsToPharmDictCtrl('sti_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_STI_TYPE;?>');
	    linkDynamicActionsToPharmDictCtrl('reproductive_health_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REPRODUCTIVE_HEALTH_TYPE;?>');
	    linkDynamicActionsToPharmDictCtrl('tuberculosis_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_TUBERCULOSIS_TYPE;?>');
	    linkDynamicActionsToPharmDictCtrl('ovc_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_OVC_TYPE;?>');
	    

/*** START Bind of OnChange ***/        
        $('input[name = "is_referred_in"]').bind('change', function(){
            checkIsReferredIn();
        });
        $('input[name = "is_referred_out"]').bind('change', function(){
            checkIsReferredOut();
        });
        $('input[name = "is_htc_done"]').bind('change', function(){
            checkIsHtcDone();
        });
        $('input[name = "is_palliative_services_to_plwha"]').bind('change', function(){
            checkIsPalliativeServicesToPlwha();
        });
        $('input[name = "is_sti_services"]').bind('change', function(){
            checkIsStiServices();
        });
        $('input[name = "is_reproductive_health_services"]').bind('change', function(){
            checkIsReproductiveHealthServices();
        });
        $('input[name = "is_tuberculosis_services"]').bind('change', function(){
            checkIsTuberculosisServices();
        });
        $('input[name = "is_ovc_services"]').bind('change', function(){
            checkIsOvcServices();
        });
/*** END Bind of OnChange ***/        
        
        checkIsReferredIn();
        checkIsReferredOut();
        checkIsHtcDone();
        checkIsPalliativeServicesToPlwha();
        checkIsStiServices();
        checkIsReproductiveHealthServices();
        checkIsTuberculosisServices();
        checkIsOvcServices();
        
        $("#date_of_visit").datepicker({dateFormat : 'yy-mm-dd', appendText: "(yyyy-mm-dd)"});
});
</script>	


<?php if(!empty($this->error)) : ?>
<div class="form_errors"><?php echo $this->error;?></div>
<?php endif;?>
<form id="main_form" class="zend_form" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('action' => 'create', 'type' => $this->type));?>">
<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="required"><label for="id_pharmacy"><?php echo $this->translate(_("Pharmacy"));?></label></div></td>
   <td>
     <select name="id_pharmacy" id="id_pharmacy">
        <option value=''></option>
<?php
    foreach($this->pharmacies as $key=>$value) {
        $selectedStr = ($key == $this->idPharmacy) ? 'selected' : '';
        printf("<option value='%s' %s>%s</option>", $key, $selectedStr, $value);
    }
?>     
     </select>&nbsp;
<?php if ($this->allow_create_pharmacy) : ?>
     <a id="link-add-pharmacy" href="#"><?php echo $this->translate(_("Add Pharmacy"));?></a>
<?php endif;?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><label for="id_patient"><?php echo $this->translate(_("Patient"));?></label></div></td>
   <td>
     <input type="hidden" name="id_patient" id="id_patient" value="<?php echo $this->id_patient?>" />
     <input type="text" size="32" name="patient_name" id="patient_name" value="<?php echo $this->patientName;?>">&nbsp;     
<?php if ($this->allow_create_patient) : ?>
     <a id="link-add-patient" href="#"><?php echo $this->translate(_("Add Patient"));?></a>
<?php endif;?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><label for="date_of_visit"><?php echo $this->translate(_("Date of Visit"));?></label></div></td>
   <td>
     <input type="text" name="date_of_visit" id="date_of_visit" value="<?php echo $this->dateOfVisit;?>">     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Referral Services Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_in"><?php echo $this->translate(_("Referred in?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_in" id="is_referred_in_0" value="0" <?php if(!$this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_in" id="is_referred_in_1" value="1" <?php if($this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_in">
   <td></td>
   <td>
     <select name="referred_in[]" id="referred_in" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_in"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_out"><?php echo $this->translate(_("Referred out?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_out" id="is_referred_out_0" value="0" <?php if(!$this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_out" id="is_referred_out_1" value="1" <?php if($this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_out">
   <td></td>
   <td>
     <select name="referred_out[]" id="referred_out" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_out"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referral_completed"><?php echo $this->translate(_("Was the referral completed?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referral_completed" id="is_referral_completed_0" value="0" <?php if(!$this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referral_completed" id="is_referral_completed_1" value="1" <?php if($this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_hiv_risk_assesment_done"><?php echo $this->translate(_("HIV risk assessment & counseling done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_0" value="0" <?php if(!$this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_1" value="1" <?php if($this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("HCT Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done"><?php echo $this->translate(_("HIV Testing done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done" id="is_htc_done_0" value="0" <?php if(!$this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done" id="is_htc_done_1" value="1" <?php if($this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_htc_result_id">
   <td></td>
   <td>
     <select name="htc_result_id" id="htc_result_id">
     </select>&nbsp;
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_client_received_htc"><?php echo $this->translate(_("Was the client Counseled, Tested & received results?"));?></label></div></td>
   <td>
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_0" value="0" <?php if(!$this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_1" value="1" <?php if($this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done_in_current_pharmacy"><?php echo $this->translate(_("Was the HCT done in your Pharmacy?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_0" value="0" <?php if(!$this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_1" value="1" <?php if($this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Services Provided Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_palliative_services_to_plwha"><?php echo $this->translate(_("Palliative Care Services to PLWHAs"));?></label></div></td>
   <td>
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_0" value="0" <?php if(!$this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_1" value="1" <?php if($this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_palliative_care_type">
   <td></td>
   <td>
     <select name="palliative_care_type[]" id="palliative_care_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-palliative_care_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_sti_services"><?php echo $this->translate(_("STI Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_sti_services" id="is_sti_services_0" value="0" <?php if(!$this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_sti_services" id="is_sti_services_1" value="1" <?php if($this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_sti_type">
   <td></td>
   <td>
     <select name="sti_type[]" id="sti_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-sti_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_reproductive_health_services"><?php echo $this->translate(_("Reproductive Health Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_0" value="0" <?php if(!$this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_1" value="1" <?php if($this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_reproductive_health_type">
   <td></td>
   <td>
     <select name="reproductive_health_type[]" id="reproductive_health_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-reproductive_health_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_tuberculosis_services"><?php echo $this->translate(_("Tuberculosis Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_0" value="0" <?php if(!$this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_1" value="1" <?php if($this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_tuberculosis_type">
   <td></td>
   <td>
     <select name="tuberculosis_type[]" id="tuberculosis_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-tuberculosis_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_ovc_services"><?php echo $this->translate(_("OVC Care and Support Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_ovc_services" id="is_ovc_services_0" value="0" <?php if(!$this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_ovc_services" id="is_ovc_services_1" value="1" <?php if($this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_ovc_type">
   <td></td>
   <td>
     <select name="ovc_type[]" id="ovc_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-ovc_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
 </table>
</div>


<input type="submit" name="save" value="<?php echo $this->translate(_("Save"));?>"/>     
</form>


<div id="dlg-add-dict-entity" title="<?php echo $this->translate(_("Add"));?>" type_id="" list_element_id="">
  <p class="errorInfo"></p>
  <form>
    <label for="name"><?php echo $this->translate(_("Name"));?></label>
    <input type="text" name="name" id="add-dict-entity-name" class="text ui-widget-content ui-corner-all" size="56"/>
  </form>
</div>

<div id="dlg-edit-dict-entity" title="<?php echo $this->translate(_("Modify"));?>" type_id="" list_element_id="">
  <p class="errorInfo"></p>
  <form>
    <label for="name"><?php echo $this->translate(_("Name"));?></label>
    <input type="text" name="name" id="edit-dict-entity-name" class="text ui-widget-content ui-corner-all" size="56"/>
    <input type="hidden" name="id" id="edit-dict-entity-id" />
    </form>
</div>

<div id="dlg-remove-dict-entity"style="display: none;" title="<?php echo $this->translate(_("Warning"));?>" type_id="" list_element_id="" dict_id="">
  <p class="errorInfo"></p>
  <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
  <?php echo $this->translate(_("<div id='remove-dict-entity-name' style='font-weight: bold;'></div> will be removed. Are You sure?"));?>
</div>