<?php
$this->headScript()->appendFile('/js/internalAddress.js');
$this->headScript()->appendFile('/js/pageAsDlg.js');
$this->headScript()->appendFile('/js/dictEntitiesCtrl.js');
$this->headScript()->appendFile('/js/jquery/plugin/showLoading/jquery.showLoading.min.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.ui.position.js');
$this->headScript()->appendFile('/js/jquery/plugin/contextMenu/jquery.contextMenu.js');
$this->headScript()->appendFile('/js/i18next-1.6.3.min.js');

$this->headLink()->appendStylesheet('/css/showLoading.css');
$this->headLink()->appendStylesheet('/js/jquery/plugin/contextMenu/jquery.contextMenu.css');

$textForEmptyAdrStopDate = $this->translate(_("Ongoing"));
?>
<style type="text/css" title="currentStyle">
a {
    cursor: pointer;
    text-decoration: underline;
}
</style>

<script type="text/javascript" charset="utf-8">
<?php foreach($this->dictEntities as $key=>$values) :?>
dictEntitiesCtrl.addSelected(<?php echo $key;?>, [<?php if(is_array($values)) echo join(" , ", $values);?>]);
<?php endforeach; ?>

    function checkIsReferredFrom()
    {
        if(0 == $('input:radio[name=is_referred_from]:checked').val()) {
            $('#row_referred_from').hide();
        }
        else {
            $('#row_referred_from').show();
        }
    }

    function checkIsReferredIn()
    {
        if(0 == $('input:radio[name=is_referred_in]:checked').val()) {
            $('#row_referred_in').hide();
        }
        else {
            $('#row_referred_in').show();
        }
    }
    
    function checkIsReferredOut()
    {
        if(0 == $('input:radio[name=is_referred_out]:checked').val()) {
            $('#row_referred_out').hide();
        }
        else {
            $('#row_referred_out').show();
        }
    }

    function checkIsHtcDone()
    {
        if(0 == $('input:radio[name=is_htc_done]:checked').val()) {
            $('#row_htc_result_id').hide();
        }
        else {
            $('#row_htc_result_id').show();
        }
    }

    function checkIsPalliativeServicesToPlwha()
    {
        if(0 == $('input:radio[name=is_palliative_services_to_plwha]:checked').val()) {
            $('#row_palliative_care_type').hide();
        }
        else {
            $('#row_palliative_care_type').show();
        }
    }

    function checkIsStiServices()
    {
        if(0 == $('input:radio[name=is_sti_services]:checked').val()) {
            $('#row_sti_type').hide();
        }
        else {
            $('#row_sti_type').show();
        }
    }
    
    function checkIsReproductiveHealthServices()
    {
        if(0 == $('input:radio[name=is_reproductive_health_services]:checked').val()) {
            $('#row_reproductive_health_type').hide();
        }
        else {
            $('#row_reproductive_health_type').show();
        }
    }

    function checkIsTuberculosisServices()
    {
        if(0 == $('input:radio[name=is_tuberculosis_services]:checked').val()) {
            $('#row_tuberculosis_type').hide();
        }
        else {
            $('#row_tuberculosis_type').show();
        }
    }

    function checkIsMalariaServices()
    {
        if(0 == $('input:radio[name=is_malaria_services]:checked').val()) {
            $('#row_malaria_type').hide();
        }
        else {
            $('#row_malaria_type').show();
        }
    }
    
    function checkIsOvcServices()
    {
        if(0 == $('input:radio[name=is_ovc_services]:checked').val()) {
            $('#row_ovc_type').hide();
        }
        else {
            $('#row_ovc_type').show();
        }
    }
    
    function checkIsAdrScreened()
    {
        if(0 == $('input:radio[name=is_adr_screened]:checked').val()) {
            $('input[name = "is_adr_symptoms"]').attr("disabled", 'disabled');
            $('#is_adr_symptoms_0').attr('checked', 'checked');
        }
        else {
            $('input[name = "is_adr_symptoms"]').removeAttr("disabled");
        }
        checkIsAdrSymptoms();
    }

    function checkIsAdrSymptoms()
    {
        if(0 == $('input:radio[name=is_adr_symptoms]:checked').val()) {
            $('#row_adr_severity_id').hide();
        }
        else {
            $('#row_adr_severity_id').show();
        }
    }

    function checkIsAdrInterventionProvided()
    {
        if(0 == $('input:radio[name=is_adr_intervention_provided]:checked').val()) {
            $('#row_adr_intervention').hide();
        }
        else {
            $('#row_adr_intervention').show();
        }
    }
    

    function checkAdrStopDate()
    {
        var val = $('#adr_stop_date').val();
        if('' == val || '<?php echo $textForEmptyAdrStopDate;?>' == val) {
            $('#adr_stop_date').val('<?php echo $textForEmptyAdrStopDate;?>');
            $('#adr_stop_date').css('color', '#e6e6e6');
        }
        else {
            $('#adr_stop_date').css('color', '#000000');
        }
    }
    
    $(document).ready(function() {
        internalAddress.setUrlBase('<?php echo $this->url(array('controller' => '__controller__', "action" => "__action__"), null, true); ?>');

        i18n.init({
            resGetPath: internalAddress.loadI18nDict()
            ,dynamicLoad: true 
            ,getAsync: false
            ,lng: '<?php echo Zend_Registry::get('Zend_Locale');?>'
            ,ns: 'js_resources'
            ,fallbackLng: false
        });
        
        dictEntitiesCtrl.init();
        dictEntitiesCtrl.addCtrl('referred_from', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_FROM;?>');
        dictEntitiesCtrl.addCtrl('referred_in', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_IN;?>');
        dictEntitiesCtrl.addCtrl('referred_out', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REFERRED_OUT;?>');
        dictEntitiesCtrl.addCtrl('htc_result_id', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_HTC_RESULT;?>');
        dictEntitiesCtrl.addCtrl('palliative_care_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_PALLIATIVE_CARE_TYPE;?>');
        dictEntitiesCtrl.addCtrl('sti_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_STI_TYPE;?>');
        dictEntitiesCtrl.addCtrl('reproductive_health_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_REPRODUCTIVE_HEALTH_TYPE;?>');
        dictEntitiesCtrl.addCtrl('tuberculosis_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_TUBERCULOSIS_TYPE;?>');
        dictEntitiesCtrl.addCtrl('malaria_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_MALARIA_TYPE;?>');
        dictEntitiesCtrl.addCtrl('ovc_type', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_OVC_TYPE;?>');
        dictEntitiesCtrl.addCtrl('adr_intervention', '<?php echo TrustCare_Model_PharmacyDictionary::DTYPE_COMMUNITY_ADR_INTERVENTION_TYPE;?>');
        
        $('#main_form').submit(function() {
            if('<?php echo $textForEmptyAdrStopDate?>' == $('#adr_stop_date').val()) {
                $('#adr_stop_date').val('');
            }
            if('1' == $("#is_commited option:selected").val()) {
                if(window.confirm(i18n.translate("Do You want to fill NAFDAC form at next step?"))) {
                    $('#id_generate_nafdac_form').val('1');
                }
            }
            
            return true;
        });

        

/*** START Bind of OnChange ***/        
        $('input[name = "is_referred_from"]').bind('change', function(){
            checkIsReferredFrom();
        });
        $('input[name = "is_referred_in"]').bind('change', function(){
            checkIsReferredIn();
        });
        $('input[name = "is_referred_out"]').bind('change', function(){
            checkIsReferredOut();
        });
        $('input[name = "is_htc_done"]').bind('change', function(){
            checkIsHtcDone();
        });
        $('input[name = "is_palliative_services_to_plwha"]').bind('change', function(){
            checkIsPalliativeServicesToPlwha();
        });
        $('input[name = "is_sti_services"]').bind('change', function(){
            checkIsStiServices();
        });
        $('input[name = "is_reproductive_health_services"]').bind('change', function(){
            checkIsReproductiveHealthServices();
        });
        $('input[name = "is_tuberculosis_services"]').bind('change', function(){
            checkIsTuberculosisServices();
        });
        $('input[name = "is_malaria_services"]').bind('change', function(){
            checkIsMalariaServices();
        });
        $('input[name = "is_ovc_services"]').bind('change', function(){
            checkIsOvcServices();
        });
        $('input[name = "is_adr_screened"]').bind('change', function(){
            checkIsAdrScreened();
        });
        $('input[name = "is_adr_symptoms"]').bind('change', function(){
            checkIsAdrSymptoms();
        });
        $('input[name = "is_adr_intervention_provided"]').bind('change', function(){
            checkIsAdrInterventionProvided();
        });
/*** END Bind of OnChange ***/        
        
        checkIsReferredFrom();
        checkIsReferredIn();
        checkIsReferredOut();
        checkIsHtcDone();
        checkIsPalliativeServicesToPlwha();
        checkIsStiServices();
        checkIsReproductiveHealthServices();
        checkIsTuberculosisServices();
        checkIsMalariaServices();
        checkIsOvcServices();
        checkIsAdrScreened();
        checkIsAdrInterventionProvided();
        
        $("#adr_start_date").datepicker({dateFormat : 'yy-mm-dd', appendText: "(yyyy-mm-dd)"});
        $("#adr_stop_date").datepicker({dateFormat : 'yy-mm-dd', appendText: "(yyyy-mm-dd)"});
        $("#adr_stop_date").bind('change', function(){
            checkAdrStopDate();
        });
        checkAdrStopDate();
        
});
</script>   


<?php if(!empty($this->error)) : ?>
<div class="form_errors"><?php echo $this->error;?></div>
<?php endif;?>
<form id="main_form" class="zend_form" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('action' => 'edit'));?>">
<input type="hidden" name="generate_nafdac_form" id="id_generate_nafdac_form" value="0"/>
<div class="tab_header"><?php echo $this->translate(_("General Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="required"><?php echo $this->translate(_("Pharmacy"));?></div></td>
   <td><?php echo $this->pharmacyName;?></td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><?php echo $this->translate(_("Patient"));?></div></td>
   <td><?php echo $this->patientModel->showNameAs();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="required"><?php echo $this->translate(_("Date of Visit"));?></div></td>
   <td><?php echo $this->formModel->getDateOfVisit();?></td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_first_visit_to_pharmacy"><?php echo $this->translate(_("Is this the FIRST encounter?"));?></label></div></td>
   <td>
     <input type="radio" name="is_first_visit_to_pharmacy" id="is_first_visit_to_pharmacy_1" value="1" <?php if($this->isFirstVisitToPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
     <input type="radio" name="is_first_visit_to_pharmacy" id="is_first_visit_to_pharmacy_0" value="0" <?php if(!$this->isFirstVisitToPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="hiv_status"><?php echo $this->translate(_("HIV Status"));?></label></div></td>
   <td>
     <select name="hiv_status" id="hiv_status">
<?php
    foreach($this->hivStatuses as $key=>$value) {
        $selectedStr = ($key == $this->hivStatus) ? 'selected' : '';
        printf("<option value='%s' %s>%s</option>", $key, $selectedStr, $value);
    }
?>     
       </select>
     </td>
  </tr>
  </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Referral Services Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_from"><?php echo $this->translate(_("Referred Source?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_from" id="is_referred_from_0" value="0" <?php if(!$this->isReferredFrom) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_from" id="is_referred_from_1" value="1" <?php if($this->isReferredFrom) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_from">
   <td></td>
   <td>
     <select name="referred_from[]" id="referred_from" multiple size="5">
     </select>&nbsp;
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_in"><?php echo $this->translate(_("Referred In?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_in" id="is_referred_in_0" value="0" <?php if(!$this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_in" id="is_referred_in_1" value="1" <?php if($this->isReferredIn) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_in">
   <td></td>
   <td>
     <select name="referred_in[]" id="referred_in" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_in"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referred_out"><?php echo $this->translate(_("Referred Out?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referred_out" id="is_referred_out_0" value="0" <?php if(!$this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referred_out" id="is_referred_out_1" value="1" <?php if($this->isReferredOut) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_referred_out">
   <td></td>
   <td>
     <select name="referred_out[]" id="referred_out" multiple size="5">
     </select>&nbsp;
     <a id="link-add-referred_out"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_referral_completed"><?php echo $this->translate(_("Was the referral completed?"));?></label></div></td>
   <td>
     <input type="radio" name="is_referral_completed" id="is_referral_completed_0" value="0" <?php if(!$this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_referral_completed" id="is_referral_completed_1" value="1" <?php if($this->isReferralCompleted) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("HCT Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_hiv_risk_assesment_done"><?php echo $this->translate(_("HIV risk assessment & counseling done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_0" value="0" <?php if(!$this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_hiv_risk_assesment_done" id="is_hiv_risk_assesment_done_1" value="1" <?php if($this->isHivRiskAssesmentDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done"><?php echo $this->translate(_("HIV Testing done?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done" id="is_htc_done_0" value="0" <?php if(!$this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done" id="is_htc_done_1" value="1" <?php if($this->isHtcDone) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_htc_result_id">
   <td></td>
   <td>
     <select name="htc_result_id" id="htc_result_id">
     </select>&nbsp;
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_client_received_htc"><?php echo $this->translate(_("Was the client Counseled, Tested & received results for HIV?"));?></label></div></td>
   <td>
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_0" value="0" <?php if(!$this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_client_received_htc" id="is_client_received_htc_1" value="1" <?php if($this->isClientReceivedHtc) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_htc_done_in_current_pharmacy"><?php echo $this->translate(_("Was the HCT done in your Pharmacy?"));?></label></div></td>
   <td>
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_0" value="0" <?php if(!$this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_htc_done_in_current_pharmacy" id="is_htc_done_in_current_pharmacy_1" value="1" <?php if($this->isHtcDoneInCurrentPharmacy) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
 </table>
</div>

<div class="tab_header"><?php echo $this->translate(_("Services Provided Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_palliative_services_to_plwha"><?php echo $this->translate(_("Palliative Care Services to PLWHAs"));?></label></div></td>
   <td>
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_0" value="0" <?php if(!$this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_palliative_services_to_plwha" id="is_palliative_services_to_plwha_1" value="1" <?php if($this->isPalliativeServicesToPlwha) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_palliative_care_type">
   <td></td>
   <td>
     <select name="palliative_care_type[]" id="palliative_care_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-palliative_care_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_sti_services"><?php echo $this->translate(_("STI Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_sti_services" id="is_sti_services_0" value="0" <?php if(!$this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_sti_services" id="is_sti_services_1" value="1" <?php if($this->isStiServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_sti_type">
   <td></td>
   <td>
     <select name="sti_type[]" id="sti_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-sti_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_reproductive_health_services"><?php echo $this->translate(_("Reproductive Health Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_0" value="0" <?php if(!$this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_reproductive_health_services" id="is_reproductive_health_services_1" value="1" <?php if($this->isReproductiveHealthServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_reproductive_health_type">
   <td></td>
   <td>
     <select name="reproductive_health_type[]" id="reproductive_health_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-reproductive_health_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_tuberculosis_services"><?php echo $this->translate(_("Tuberculosis Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_0" value="0" <?php if(!$this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_tuberculosis_services" id="is_tuberculosis_services_1" value="1" <?php if($this->isTuberculosisServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_tuberculosis_type">
   <td></td>
   <td>
     <select name="tuberculosis_type[]" id="tuberculosis_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-tuberculosis_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_malaria_services"><?php echo $this->translate(_("Malaria Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_malaria_services" id="is_malaria_services_0" value="0" <?php if(!$this->isMalariaServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_malaria_services" id="is_malaria_services_1" value="1" <?php if($this->isMalariaServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_malaria_type">
   <td></td>
   <td>
     <select name="malaria_type[]" id="malaria_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-malaria_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_ovc_services"><?php echo $this->translate(_("OVC Care and Support Services"));?></label></div></td>
   <td>
     <input type="radio" name="is_ovc_services" id="is_ovc_services_0" value="0" <?php if(!$this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_ovc_services" id="is_ovc_services_1" value="1" <?php if($this->isOvcServices) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_ovc_type">
   <td></td>
   <td>
     <select name="ovc_type[]" id="ovc_type" multiple size="5">
     </select>&nbsp;
     <a id="link-add-ovc_type"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
 </table>
</div>


<div class="tab_header"><?php echo $this->translate(_("ADR Tab"));?></div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_adr_screened"><?php echo $this->translate(_("Is patient screened for ADR symptoms at this visit?"));?></label></div></td>
   <td>
     <input type="radio" name="is_adr_screened" id="is_adr_screened_0" value="0" <?php if(!$this->isAdrScreened) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_adr_screened" id="is_adr_screened_1" value="1" <?php if($this->isAdrScreened) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_adr_symptoms"><?php echo $this->translate(_("Any signs/symptoms indicating adverse drug reactions (ADRs) at this visit?"));?></label></div></td>
   <td>
     <input type="radio" name="is_adr_symptoms" id="is_adr_symptoms_0" value="0" <?php if(!$this->isAdrSymptoms) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_adr_symptoms" id="is_adr_symptoms_1" value="1" <?php if($this->isAdrSymptoms) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="adr_start_date"><?php echo $this->translate(_("ADR Start Date"));?></label></div></td>
   <td>
     <input type="text" name="adr_start_date" id="adr_start_date" value="<?php echo $this->adrStartDate;?>">     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="adr_stop_date"><?php echo $this->translate(_("ADR Stop Date"));?></label></div></td>
   <td>
     <input type="text" name="adr_stop_date" id="adr_stop_date" value="<?php echo $this->adrStopDate;?>">     
   </td>
  </tr>
  <tr>
   <td valign="top"><div class="normal"><label for="is_adr_intervention_provided"><?php echo $this->translate(_("Adverse Drug Reaction intervention provided"));?></label></div></td>
   <td>
     <input type="radio" name="is_adr_intervention_provided" id="is_adr_intervention_provided_0" value="0" <?php if(!$this->isAdrInterventionProvided) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("No"));?><br/>     
     <input type="radio" name="is_adr_intervention_provided" id="is_adr_intervention_provided_1" value="1" <?php if($this->isAdrInterventionProvided) echo 'checked';?>>&nbsp;<?php echo $this->translate(_("Yes"));?>     
   </td>
  </tr>
  <tr id="row_adr_intervention">
   <td valign="top"><div class="normal"><label for="adr_intervention"><?php echo $this->translate(_("Types of ADR intervention"));?></label></div></td>
   <td>
     <select name="adr_intervention[]" id="adr_intervention" class="pharmdict_modify_menu" multiple size="5">
     </select>&nbsp;
     <a id="link-add-adr_intervention"><?php echo $this->translate(_("Other"));?></a>
   </td>
  </tr>
 </table>
</div>

<div class="tab_header">&nbsp;</div>
<div class="tab_content">
 <table class="zend_form">
  <tr>
   <td valign="top"><div class="normal"><label for="is_commited"><?php echo $this->translate(_("Save Form as"));?></label></div></td>
   <td>
     <select name="is_commited" id="is_commited">
        <option value='0' <?php if(!$this->formModel->getIsCommited()) { echo 'selected';} ?>><?php echo $this->translate(_("Draft"));?></option>
        <option value='1' <?php if($this->formModel->getIsCommited()) { echo 'selected';} ?>><?php echo $this->translate(_("Final Result"));?></option>
     </select>
     <div class="description"><?php echo $this->translate(_("Draft can be modified later."));?></div>
   </td>
  </tr>
 </table>
</div>
  
<input type="submit" name="save" value="<?php echo $this->translate(_("Save"));?>"/>     
</form>
